### ISSUE TITLE
SeNoise Mask option layout issue

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1005]
Please take a look at this node in the attached image area. The mask option and channel components need to be placed on the next line. When the panel is adjusted to a smaller with, the mask section gets cramped.

![senoise mask layout](https://cloud.githubusercontent.com/assets/7956901/10926513/23fa6ade-8266-11e5-99fc-42c4bc108cdd.png)

**Comment by devernay** [comment]
That's a bug: the "replace" parameter, and not the mask parameters, should be on the same line as the channels selector.
For me, the channel selector should always be on top, because it says something important about *what* is being processed and not the output of the plugin, so it should be the first parameter of the plugin and not a secondary one. JC Levet and @MrKepzie decided that it should be on the bottom, which does not reflect what it really does.
That bug should be easy to fix, but then should the "replace" check box be moved to the bottom? This hides the main functionality of the plugin (should it *generate* noise or *add* noise?)

**Comment by MrKepzie** [comment]
Closing the bug, discussion is still opened
