### ISSUE TITLE
TrackerPM: pattern reference frame + track every x frames ?

### ISSUE THREAD

**Issue by mathiastesar** [MrKepzie/Natron#1006]
Hi,
is there a way to track every x frames instead of every frame ?

**Comment by blackearth2014** [comment]
Not yet but what does that benefits?

**Comment by devernay** [comment]
the slower the motion, the better the tracking, so it is always better to track every frame.
However, there is more drift.
What the current tracker misses is a parameter that says which frame contains the reference pattern for tracking.
For now, it is *always* the previous frame, but it would be *very easy* to have a parameter that gives the reference frame, either as an absolute or relative frame number (with a "relative" checkbox), so that the drift is heavily reduced. This parameter could even be animated, so that you track with reference frame 1 until the tracking loses the pattern, then on the frame before the pattern was lost you set the reference frame and continue tracking. This would give an almost zero drift at very little cost.

**Comment by devernay** [comment]
fixed in 2.1
