### ISSUE TITLE
Feature Request:  Allow basic math operations in inputs

### ISSUE THREAD

**Issue by azerupi** [MrKepzie/Natron#1010]
Allowing basic math operations in input boxes would be very useful. Natron would then evaluate the expression for you instead of having to do the calculations mentally.

**Comment by MrKepzie** [comment]
Basically we could try to parse it as a Python expression, if it is valid we then keep it, otherwise we just fallback on the last valid value. 
I think this is clearer if we keep it an expression anyway, because internally this is what it is going to happen under the hood, the user better be aware of what's going on.

**Comment by azerupi** [comment]
That would be perfect!  :)

**Comment by rcspam** [comment]
Very useful, but impossible to 'clear expression' in the menu when multiple dimensions.
When try some value, it should be simple to remove it as well, perhaps  with a "del" or 'backspace' or a shortcut.
Regards
