### ISSUE TITLE
read node and premult pb

### ISSUE THREAD

**Issue by mathiastesar** [MrKepzie/Natron#1073]
Hi team, 
i m not sure it s an issue, i probably might do something wrong, but here is my  question.
I m adding an exr read node (the file was generated unpremultiplied from the renderer).
The read node comes with a default premult in natron, the help note says i need to add an unpremult plugin if i want it unpremultiplied.
I add it, make some color corrections after that and when i want to premultiply it again by adding a premult node nothing happens, it stays unpremultiplied.

example steps:
nuke
a) read node without auto premult ( source : half float exr no premult file) > color correct ect > premult =  the premult works
b) read node without auto premult ( source : half float exr no premult file) > force premult > unpremult > color correct ect > premult =  the premult works

natron
read node with default premult ( source : half float exr no premult file) > unpremult > color correct etc > premult = the premult doesn t work

Thanks team ;^)

**Comment by devernay** [comment]
did you set the correct value for "file premult" ?

**Comment by MrKepzie** [comment]
@mathiastesar The read nodes output premultiplied data but only for color (i.e: layers ending with RGB). Otherwise it does not actually apply any premultiplication to AOV passes but instead just set the *premultiplication* meta-data. 

We did it this way so that when reading multiple passes from a single file it would have the expected behaviour and not apply the premultiplication on everything.

**Comment by MrKepzie** [comment]
There was a bug fixed recently for "unpremultiplied" EXRs (known as unassociated alpha), see https://forum.natron.fr/t/exr-alpha-channel-issues/429/5

We will release a new RC soon with many stability fixes
