### ISSUE TITLE
Roto compositing operator bug

### ISSUE THREAD

**Issue by michaelWuensch** [MrKepzie/Natron#1084]
Hi,

I did some rotos and everything was fine. Then I saved the project. When I opened it again, some of the rotos were inverted. The solution to fix it was to change the compositing operator from "over" to something different and then again back to "over". I have to do this for all rotos everytime I open the project. For some reason when I finally render it it is completly random, some frames are correct, some use the inverted masks. It's really messy and impossible to render my project.
I am using Windows 7 and Natron 2.0 RC5

Thanks,
Michael

**Comment by MrKepzie** [comment]
Can you provide us with a minimal example to reproduce the bug ?

**Comment by michaelWuensch** [comment]
Well, I tried to analyze it in more detail. The masks are not only simply inverted, actually they are really strange. I recorded a video, so you can see what's happening when I reload the file. It also seems to be related with zooming in the viewer.

https://goo.gl/photos/ayTAszop7XBDXhK47

I forgot to change the Compositing Operator of the masks at the end of the video, which fixes the problem partly (As long as you don't change the frame and you don't try to render it).

If you need more information, please let me know. :)

**Comment by MrKepzie** [comment]
Can you send me the project privately ? Send a message on forum.natron.fr to MrKepzie

**Comment by michaelWuensch** [comment]
ok, I answered two the welcome Message on the Forum and sent you a link :)

**Comment by manuelsongokuh** [comment]
hello this issue is similar my issue old (closed) https://github.com/MrKepzie/Natron/issues/977

needed to refresh for roto to start up file ntp:
"forces a new render of the current frame."
maybe this is not fixed yet...from my issue old..

**Comment by PostPollux** [comment]
Well maybe it's somewhat similar to the issue you had. But it seems not to be fixed through that commit, otherwise this problem shouldn't appear in rc5 which is 2 weeks old while the commit was on oct 27.
So did you do another fix to close this issue now, MrKepzie? That would be awesome. Thanks. I'm just curious because normally there is a "closed in commit xxxxxxx" and I think the commit mentioned by manuelsongokuh is too old to close this issue as it still exists in rc5.
Thanks for your hard work even during the weekend. I appreciate that very much.

P.s. I'm a coworker of michaelWuensch, that's why this bugfix is important for me too, as we stumbled across it together and weren't able to render that simple key combined with some rotos.

**Comment by MrKepzie** [comment]
was fixed today

**Comment by manuelsongokuh** [comment]
thank you for my old issue same issue of @michaelWuensch 
i will check if my issue is fixed or not ok? thank you BIG to MRKEPZIE!
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:
