### ISSUE TITLE
proxy mode filtering

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1100]
proxy mode seems to downscale inputs and outputs using some sort of filter(bilinear or whaterver) instead of nearest (faster). resulting in strange behaviour when used with interger "footages" (ID passes form blender).

Also keyer won't show the same result in proxy and normal mode because of the noise reduction that occured with the filter

Proposal: add an button in the viewer to use nearest filtering

as a result, the cache could be reused on pixel already calculated and proxy mode will be faster and more accurate

**Comment by MrKepzie** [comment]
It is mipmaps avering pixels together. Going to the nearest mode would give crappy results and would make the viewed image change from mipmap levels to others (12.5%, 25%, 50%,etc..) because elements of the image would simply disappear. 
Even if we would use that, the rendering could not be re-used for lower mipmap levels (i.e: image with higher resolution) because in Natron we re render Tiles and not simple pixels. 
Lastly, the cost of the image downsizing in Natron is negligible and I guarantee you this is not where we could gain speed.
