### ISSUE TITLE
UI issues on High DPI screens

### ISSUE THREAD

**Issue by jcdeblok** [MrKepzie/Natron#1129]
When window's UI scale is set >100%  some UI elements scale fine, other seem to have a hardcoded fixed sizes. This is a big problem when working on 4k+ displays and Surface computers. 

You can simulate the problem on a 'normal' display by settings window's UI scale to 200%, the attached screen shot has a few of the problems highlighted.

![10255782_1114327068591957_6182998150157305478_o](https://cloud.githubusercontent.com/assets/16501444/12065082/5db7af5a-afd1-11e5-9a01-8bd6a4b00aae.jpg)

**Comment by MrKepzie** [comment]
We are aware of it, I have ways to reproduce it on a mac book pro with bootcamp to enable Windows. Natron works fine on Apple retina screens because Qt works well with it, unfortunately there seem to be much less support for 4K+ displays from Qt 4.8.

We have a lot of widget size dependant on text size, and if text size is not calculated appropriately then everything falls apart, as you witness.

**Comment by devernay** [comment]
@jcdeblok can you test the latest snapshots and report, please? It should be better, though not perfect yet

**Comment by jcdeblok** [comment]
Cool, will do!

**Comment by jcdeblok** [comment]
Great job, it all looks a lot better now!

**Comment by lucas-wade** [comment]
Hi DPI 
In the node view on the bottom of a node the small arrow to connect the output from node1 to to node2 is tiny. super tiny.  
I am running Natron on Arch Linux Gnome Desktop. Using the Install download from natron.fr

**Comment by devernay** [comment]
can you please post a screenshot?
