### ISSUE TITLE
Save node vs viewer

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1139]
It seams that the viewer node and write node behave differently (probably because of premult or something similar)   when alpha goes beyond 1.0

**Comment by MrKepzie** [comment]
Can you be more explicit regarding the problem and possible show us a screencast with the difference ?

**Comment by iscream75** [comment]
left:viewer pluged on a write node
right:viewer pluged on a read node (same file)
note the 2.0 alpha value

![000149](https://cloud.githubusercontent.com/assets/16254684/12173504/7832f0ca-b557-11e5-837e-380818385228.jpg)

**Comment by MrKepzie** [comment]
I'm afraid I need more infos... such as your graphs and the setup of the nodes, it would be easier if you would send us the project file

**Comment by iscream75** [comment]
it's not graphtree speciphic, it's each time you save and load a with with some pixel with alpha value above 1.0

[bug_alpha2.0.zip](https://github.com/MrKepzie/Natron/files/82654/bug_alpha2.0.zip)

**Comment by iscream75** [comment]
also note the warning saying that the constant and the roto nodes have different frame rate.

**Comment by MrKepzie** [comment]
It's only related for me to the TGA file format: values are clamped to 1 inside and unpremultiplied, that's why when you read back with a Read node your image, it doesn't look the same. For the EXR file format it doesn't happen because values are stored with full floating point precision.

Note that when you attach a viewer to a Write node, the image displayed is not read back from the file itself but it is merely a copy from the node upstream.

**Comment by iscream75** [comment]
It happens for the exr too
Le 9 janv. 2016 14:51, "Alexandre Gauthier" <notifications@github.com> a
écrit :

**Comment by MrKepzie** [comment]
I cannot reproduce for EXR

**Comment by iscream75** [comment]
Tested with a new snapshot and I cannot reproduce it for exr ... but tga still has the bug.

**Comment by devernay** [comment]
Is it an OIIO bug ?
