### ISSUE TITLE
Exr channel messed up with sequences, ok with single frame

### ISSUE THREAD

**Issue by iscream75** [MrKepzie/Natron#1152]
Loading an exr in sequence or file mode give different result. un fortunately I can't share the sequence (3frames) publicy but I could share it by mail.

**Comment by MrKepzie** [comment]
You can send it to immarespond at gmail dot com

**Comment by iscream75** [comment]
Shared with the project file via google drive

**Comment by MrKepzie** [comment]
It's not a bug, your sequence is malformed: the first file has the layer Depth.RGBA but others have only Depth.V
Since the channels layout are assumed to be constant throughout the sequence it will not work. 
<img width="203" alt="screen shot 2016-01-12 at 12 06 20" src="https://cloud.githubusercontent.com/assets/4058448/12262008/29d63ece-b925-11e5-86b0-58dec2f0ad09.png">
<img width="203" alt="screen shot 2016-01-12 at 12 06 24" src="https://cloud.githubusercontent.com/assets/4058448/12262009/2afc86aa-b925-11e5-9ad7-b7583fe8b65f.png">
