### ISSUE TITLE
Segfault with python and Read nodes

### ISSUE THREAD

**Issue by speedr972** [MrKepzie/Natron#1169]
Hello,
I'm trying to use a script generating automatically an node graph, but when I try to set a filename to read nodes (ReadFFmpeg or ReadOIIO), a segmentation fault is caught. This error happens either with the init.py or an independant script

Here is the trace given on the terminal:

Natron Version 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<
init.py script loaded
initGui.py script not loaded
Caught segmentation fault (SIGSEGV) from thread Main(0x1e6a4b0), faulty address is 0x7f65f3726aea from 0
Backtrace:
[Frame 1]: /lib/x86_64-linux-gnu/libc.so.6(strlen+0x2a) [0x7f65f3726aea]
[Frame 2]: /lib/x86_64-linux-gnu/libc.so.6(strlen+0x2a) [0x7f65f3726aea]
[Frame 3]: /home/oroneos/Natron2/bin/../lib/libshiboken-python2.7.so.1.2(+0x14133) [0x7f65f6bc0133]
[Frame 4]: /home/oroneos/Natron2/bin/Natron() [0xd27d20]
[Frame 5]: /home/oroneos/Natron2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x46be) [0x7f65f79d259e]
[Frame 6]: /home/oroneos/Natron2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x482e) [0x7f65f79d270e]
[Frame 7]: /home/oroneos/Natron2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x80d) [0x7f65f79d3fbd]
[Frame 8]: /home/oroneos/Natron2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCode+0x32) [0x7f65f79d40f2]
[Frame 9]: /home/oroneos/Natron2/bin/../lib/libpython2.7.so.1.0(PyRun_StringFlags+0x79) [0x7f65f79feaf9]
[Frame 10]: /home/oroneos/Natron2/bin/Natron(_ZN6Natron21interpretPythonScriptERKSsPSsS2_+0x4d) [0x9d64ed]
[Frame 11]: /home/oroneos/Natron2/bin/Natron(_ZN11AppInstance28execOnProjectCreatedCallbackEv+0x446) [0x9c4806]
[Frame 12]: /home/oroneos/Natron2/bin/Natron(_ZN14GuiAppInstance4loadERK6CLArgs+0x6f2) [0x6e9e92]
[Frame 13]: /home/oroneos/Natron2/bin/Natron(_ZN10AppManager14newAppInstanceERK6CLArgs+0x3a) [0x9d87ea]
[Frame 14]: /home/oroneos/Natron2/bin/Natron(_ZN10AppManager24loadInternalAfterInitGuiERK6CLArgs+0x957) [0x9e3637]
[Frame 15]: /home/oroneos/Natron2/bin/../lib/libQtCore.so.4(_ZN11QMetaObject8activateEP7QObjectPKS_iPPv+0x2da) [0x7f65f48d403a]

Config : Ubuntu 14.04LTS

Thanks

**Comment by MrKepzie** [comment]
We updated recently the command line mode and you should try newer snapshots : Natron-latest-Linux-x86_64bit-snapshot.tgz <http://downloads.natron.fr/Linux/snapshots/64bit/files/Natron-latest-Linux-x86_64bit-snapshot.tgz> 

I also updated the manual with some example for auto-creation of graphs and how it is supposed to be setup (it seems to correspond to your use-case): 

http://natron.readthedocs.org/en/workshop/natronexecution.html#example

init.py is not a place where you would create nodes etc… because the Project instance does not even exist yet!

The preferred method is to pass a script to the command-line arguments of Natron. You could also pass a .ntp script and configure it with a python script with either the -cmd option or the —onload option. See the link above to the documentation for more informations;

**Comment by devernay** [comment]
Was the segfault fixed? Even if init.py is not the right place, it should not segfault.

**Comment by speedr972** [comment]
It seems to work.
Thank you
