### ISSUE TITLE
EDL (edit decision list) import

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1170]
Natron could import EDLs (CMX3600 and EDLs from most common software), in order to preview effects on an edited movie.
It should create one reader per clip, and edit them using the dopesheet and simple effects (mainly dissolve)

**Comment by blackearth2014** [comment]
This will be a GOD send to have this feature, but FCPx is my main editor. It only export FCPXML. Will that be supported in the future?

**Comment by devernay** [comment]
Yes, we will probably first focus on CMX3600, Avid, and FCPXML.
I also found Vegas EDL samples at http://forum.videohelp.com/threads/321056-EDL-File-Format but could not find specs anywhere.

- FCPXML: https://documentation.apple.com/en/finalcutpro/usermanual/index.html#chapter=96%26section=1%26tasks=true
- CMX3600: http://xmil.biz/EDL-X/CMX3600.pdf
- Blender EDL (CMX3600) import code: https://git.blender.org/gitweb/gitweb.cgi/blender-addons.git/tree/HEAD:/io_sequencer_edl

**Comment by blackearth2014** [comment]
Cool Breeze

**Comment by blackearth2014** [comment]
Will there be a limit to the length of the movie clips exported to EDL. Will applications like Resolve, Assimilate Scratch or Baseight be a inspiration on how they see clips on a timeline. If each EDL has like 30 individual read nodes, the node graph can get crowded quick.

**Comment by blackearth2014** [comment]
I can see how a group will be important in this case.

**Comment by nicholascarroll** [comment]
EDL is an antiquated format that talks about reels and not shots, and timecodes not frames. 

You say" in order to preview effects on an edited movie." Can I suggest looking at this in the context of the overall workflow or pipeline? I invite you to forum topic I have opened for this: [Pipleline or Workflow between editor, compositor and VFX](https://forum.natron.fr/t/pipeline-or-workflow-between-editor-compositor-and-vfx/550).

**Comment by nicholascarroll** [comment]
Hope this is helpful: from http://www.digital-intermediate.co.uk/DI/DIconform.htm:
![](https://cloud.githubusercontent.com/assets/1062708/13587711/281db7ae-e51e-11e5-9e51-3f0c9287fd29.jpg)

**Comment by nicholascarroll** [comment]
Blender project created a Python CMX3600 EDL parser that you could use - called parse_edl.py. Using python would make it easy for users to adjust the file definition for the slight variations in EDL formats out there.

**Comment by devernay** [comment]
@nicholascarroll Thanks, it's already mentioned in the 2nd comment.

**Comment by mash-graz** [comment]
> EDL is an antiquated format that talks about reels and not shots, and timecodes not frames. [EDIT: Sorry this is probably a bit overboard, uninformed statement, as I am told EDL is still very much the standard in today].

a small subset of EDL is still used as least common denominator of project data.

some practical notes about actual use of EDL:
usually for every track one single EDL file is used, because in CMX3600 days the number of tracks was quite limited. but the limitations of file/real naming, audio video relations etc. are quite insufficient for actual project representation. many EDL implementations are very picky on whitespace conventions used in EDLs (http://www.editware.com/Editware-DOCs/EDLformat.PDF).

support for MLT XML project files, like used in shotcut, kdenlive, and flowblade, would be very useful.

MLT could also be used as an interesting solution, to get a faster preview and audio handling for a natron timeline beside the more processing intensive usual node processing. synfig is using MLT in this way to handle the audio processing.

**Comment by nicholascarroll** [comment]
The modern equivalent of EDL is AAF. It is supported by:
- Lightworks
- Avid Media Composer
- Sony Vegas Pro
- Resolve
- Premiere Pro
- Nuke Studio
- Assimilate Scratch
- Mistika
- ProTools
- Digita Performer
- Nuendo
etc...

I have logged enhancement request #1225 to make a simple start to this by having a read node.

**Comment by mash-graz** [comment]
the advanced authoring format (AAF) uses a very strange binary format, that is hard to handle by free software. but it's indeed a well known exchange format supported by many commercial applications.

**Comment by bonalex01** [comment]
Hi, 
I see some people are already working on a connexion between AAF and python.
This may help for what we need here.
[https://github.com/markreidvfx/pyaaf](url)

**Comment by tin2tin** [comment]
EDL export is now implemented in Shotcut: https://www.shotcut.org/blog/new-release-1606/

**Comment by tin2tin** [comment]
EDL export is also implemented in Flowblade now: [https://github.com/jliljebl/flowblade/issues/252](https://github.com/jliljebl/flowblade/issues/252)

EDL import in Natron would be brilliant for finalizing(eg. color grading, reframing, image correcting, retiming, vfx = no need for close sourced Davinci) an edited film project. 

I'm still hoping for Ardour to add EDL import, so you could have an entire open sourced pipeline for film production.

**Comment by sobotka** [comment]
+1 to FCPXML, as it was very well specified prior to the more recent implementations, including splines and other useful blocking / timing metadata that might be passed from an NLE.

I'd add that it wouldn't be a horrible blueprint for an open interchange format, should Natron choose to implement one that could evolve.

**Comment by tin2tin** [comment]
An extreamly simple nuke script to import an edl as a string of notes(it's so barebones that it will only pass as a test-of-concept): 
http://snipplr.com/view/46281/pxedlreader/

**Comment by tin2tin** [comment]
Now Blender also can export EDL: https://blenderartists.org/forum/showthread.php?418606-EDL-export-script-help-needed!&p=3172180&viewfull=1#post3172180

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#137
