### ISSUE TITLE
Presets enhancements

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1185]
Is possible to extend or increase more information in the node's info tab for things like loaded preset data of name and location the preset was loaded from.  I am creating some pseudo looks to share with my NatronNation group using the Color Correction and Colorlookup nodes. At the moment, every node that can save and load a preset saves with the suffix .NPS. It will be nice if we can tell what folder location and the name of the preset came from.

Also can each node have an auto naming with nodes name in the title as dot.NameOfnode or each node have a different preset extension.

**Comment by MrKepzie** [comment]
In 2.2 Presets will be parsed in Natron search paths (same as PyPlugs) and if found, Natron will add them as a submenu item from the toolbar and in the tab menu with the name of the node followed by the name of the presets in parenthesis, e.g:


    Blur->
             Blur (default)
             Blur (small)
             Blur (myBlur)
             ...

A python function will also be able to load a node from a nps file. 
It will also be possible to have presets for groups. Another way of emulating a PyPlug would be to make a group from scratch, customise it and export it as a presets. But with this method, you won't be able to add custom callbacks and code to tailor your plug-in, but may be more friendly for non coders.

The reason why this is added is because in 2.2 the user can customize the viewer node as a group, e.g :

<img width="1552" alt="screen shot 2016-08-14 at 22 50 17" src="https://cloud.githubusercontent.com/assets/4058448/17654494/adba366e-6271-11e6-9d03-ae559eb5eb7a.png">

The user can add internal nodes for display and tweek the interface in the toolbar above to add parameters, remove or edit them.

Once customised, you can export the viewer configuration as a preset that is then available in the menu Image->Viewer->Viewer(MyPreset)

**Comment by blackearth2014** [comment]
Cool Breeze

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#140
