### ISSUE TITLE
Last linux snapshot doesn't start

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#1249]
/Natron2/bin/Natron: undefined symbol: _ZTI17QThreadPoolThread

**Comment by olear** [comment]
Reinstall the 'Natron libraries' package from 'NatronSetup'.

**Comment by adallafontana** [comment]
I have tried to reinstall but I have the same issue, what do you mean, I need to download a new "setup"

**Comment by olear** [comment]
If you had an existing snapshot installation before v2.0.1 and upgraded using NatronSetup you will have a "broken installation", since we did some changes to the "Natron Libraries" package and did not update the version number, so you need to start NatronSetup, go to package manager and remove the "Natron Libraries", then restart NatronSetup, go to package manager and install the "Natron Libraries".

The version as been bumped, but we have not built a new snapshot.

This only affect snapshot upgrades.

**Comment by adallafontana** [comment]
ok thanks,
I have delete all (....seem the only option in NatronSetup) and reinstall 2.0.1 with the debian 64 package,
Natron works, now the folder is in opt, but I don't have a NatronSetup anymore for future update, there is a custom package for this? On the site on snapshot link seem there are only the single file (lib, ocio, etc....).

**Comment by olear** [comment]
You have several options in NatronSetup, you select "Package Manager" to manage the packages. No need to delete all.

NatronSetup are only included in the installer version, DEB/RPM are handled by your native package manager.
