### ISSUE TITLE
switch to default value 

### ISSUE THREAD

**Issue by korabkoff** [MrKepzie/Natron#1290]
### Problem
There is a short key for disabling/enabling nodes and it is very useful. Same thing with values in grade for example - I want quickly compare before and after for particular parameter. Also quick reset to default value makes life a lot more easier when working with scripts made by some one else.

Suggestion .
Switch to default value by middle click on spinner, value or value name and return back on second middle click. To seamless interaction shortcut "D" over spinner or value name can be applied instead of middle click.

**Comment by devernay** [comment]
This feature was asked before (by @blackearth2014 if I remember well)

Note that the Nuke shortcut is : 

Ctrl+LMB - Reset slider to default

We can probably easily add this shortcut (@MrKepzie ?)

**Comment by korabkoff** [comment]
Great! Where I can find list of other shortcuts?

**Comment by MrKepzie** [comment]
Menu Display--> Show Shortcut Editor.

**Comment by MrKepzie** [comment]
Implemented

**Comment by blackearth2014** [comment]
I had asked for this feature fort he Color Correct Node to have the SMH tones being able to deactivate for before and after comparison. It is a great time saver. It would be nice to have this feature for the HSVTool, ColorLookup, Color Suppress Nodes if applicable.

**Comment by MrKepzie** [comment]
How about deactivating/activating the node by pressing D ?

**Comment by devernay** [comment]
@blackearth2014:
- For HSVTool, does it make sense to selectively enable/disable Hue, Saturation/Brightness ranges? Since it is a single transform, and not separate transforms as in ColorCorrect, I'm not sure what "disable" should mean.
- For ColorLookup, since it's a per-channel transform, it seems like the channel checkboxes would do the job, don't they?
- For ColorSuppress, you can use the new Ctrl-LMB shortcut, and the restore the value using Ctrl-Z, then play with Ctrl-Shift-Z / Ctrl-Z (Ctrl-Z is currently not working in the snapshots but is being fixed)

**Comment by blackearth2014** [comment]
Cool Breeze. Now that I look at it, the HSVTool doesn't need the aforementioned features.
