### ISSUE TITLE
OFX Plugins in Windows

### ISSUE THREAD

**Issue by lubeda** [MrKepzie/Natron#1303]
This is no real bug but more a feature request.

The installer should place all OFX Plugins into the default Folder so that other tools can use the Plugins. On 64 bit Windows the folder for OFX Plugins is "c:\Program Files\Common Files\OFX". The neccesary DLLs should also be placed there. Perhaps an option in the installer would be nice, so one can decide to place the plugins into the Natron Program Folder or in the default OFX Path.

This could help to use the very cool Plugins e.g. in Hitfilm  and davinci resolve.

Greetings

**Comment by olear** [comment]
I understand why you want this, but this requires several changes to how we build and distribute the installer. This request also won't benefit Natron in any way (compared to the work needed to modify the build process/installer). I don't know what the rest of the team thinks, they may voice their opinion if it differs from mine.

I could make a separate installer for just the plugins, distributed independently of Natron, but that will get a low priority.

**Comment by lubeda** [comment]
I think a seperate installer would be fine for all who use another host for the OFX-plugins.

**Comment by devernay** [comment]
Compiling plugins for other hosts (especially on windows) is not our concern.

The problem is that we compile all plugins in a single bundle for Natron, but Fusion or Resolve users only need a few. Besides, there are lots of problems that come with plugins, and we do not want to deal with compatibility with all hosts (especially when the plugin itself uses libraries).

The source code for all plugins is available in https://github.com/devernay/openfx-misc and https://github.com/MrKepzie/openfx-io/.

There are vcproj files there, but they are probably outdated since we do not even use Visual Studio (we use MSYS2 on Windows).

Feel free to contribute new build files for Windows on these repositories, or find a Windows developper who can help you on that.

**Comment by lubeda** [comment]
:-( but I understand your arguments.
