### ISSUE TITLE
Tracker/Roto node issue Snapshot 2.1.0

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#1340]
Seem there is no way to link a Roto shape to a tracker point with the new tracker node.
If I ctrl-click on a selected curve, before I could link the shape to a tracker in the list, now I don't have option for this one.

**Comment by blackearth2014** [comment]
That feature has been depreciated for the new Tracker node in Natron 2.1 uses Blender's Plane track algorithm. In the new Tracker node you can add as many tracks that you need beyond 4 and export to a corner pin. You can use a cornerpin node before it if you need to distort image to a certain space in your footage. Furthur implementation are being added to make that process even easier.

**Comment by adallafontana** [comment]
Hi Omar,
Do you mean that I can't link a shape to one tracker alone? I need always 4 point for distort the plane.
I'm little confused, in Blender I can parent/link a shape to a single tracker, or if I want I use a planar with 4 point.

**Comment by blackearth2014** [comment]
If you are using the Natron 2.0.5 then that feature is still there. In the Master Beta version, linking Roto points to trackers are no longer available because of the plane tracker implementation. Here is a response from the developers when I had the same question

"This functionality is going to be removed as it is not useful and very clunky. The correct way to do it, and this the way the future Planar Tracker will work is to track one or multiple points and compute a CornerPin transform from the tracked data (in the Transform tab of the tracker node). The CornerPin can then be applied after a Roto/RotoPaint node to move the shapes with the motion of the tracks (if you chose Match-Move in the transform tab of the tracker).

I hope this answers your question.

**Comment by adallafontana** [comment]
I understand but for me is a wrong method, this complicate all, if you have eg. 3 masks for follow a subject, you need 3 separate roto node, 3 cornerpin, connect all and after merge the 3 masks togheter for have 1 mask that cover entire subject.
I'm thinking there is some error because this is a regression, also the tracker offset seem missing.

**Comment by MrKepzie** [comment]
The right way to do this is by tracking as many points in the shape as your want, computing a corner pin from it and linking that matrix to the Extra Matrix in the Transform tab of the roto node.

This is not yet implemented and is how will work the planar tracker. 
We removed the link of 1 point to a track because this very un-needed with the upcoming planar tracker and was difficult to maintain with architecture changes.

**Comment by adallafontana** [comment]
"computing a corner pin from it and linking that matrix to the Extra Matrix in the Transform tab of the roto node. This is not yet implemented..."

Ok, this one has some sense.

**Comment by MrKepzie** [comment]
Anyway I hope this is only a beta because the tracker algorithm works bad than in Blender.

Can you be explicit ? What do you think is bad in particular ?

**Comment by MrKepzie** [comment]
You have to set it up with the same parameters as Blender! ;)

 - The "Motion Model" parameter must be set to Trans. Rot like it is set in Blender
 - The "normalise intensities" parameter must be checked as you did in Blender
 - Make sure the search window (the outter window that you can edit in the viewer) is at least as wide as what you set in Blender (151px)
 

Regarding the speed in Natron vs Blender, this is just because we do a lot more! We give much more feedback during the tracking on the Viewer, timeline and values in the properties panel. If you want it to go faster, just disable viewer update in the toolbar in the viewer, it will go much faster.

**Comment by adallafontana** [comment]
Alexander I have tried all kind of set-up, in the screen-shot you can see the best performance on Natron tracker "15 frame", if I change the kind of tracking to loc-rot or affine, check normalize and bla bla bla.... the tracker was stopped after 2-3 frame, the only way for arrive to the end of path is insert a keys every 10 frames, but also with keys enable the tracker have serious problem to follow the nail in some point.

**Comment by MrKepzie** [comment]
Can you send me this video privately so I can test here to reproduce in both softwares ?

**Comment by adallafontana** [comment]
I have your @inria.fr address, I must send at that?

**Comment by MrKepzie** [comment]
Yes
