### ISSUE TITLE
Group nodes not reloading from Pyplug

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1356]
### Problem

When you change the internals of a group node, it doesn't update in the group nodes instantiated in the project.

**Expected behavior:** 
Expected is that when a project loads and it has a group pyplug in it, it should load the group from the pyplug definition on disk. The tooltip on the padlock icon in the group agrees with this, it says "...if you unlock...subsequent loading of this project will no longer load the group from the python script".
**Actual behavior:** 
Even if you don't unlock the group, it doesn't reflect changes to the pyplug script.
** Suggested**
Use major version to indicate the params have changed so then don't update.

**Without this fix**
without this you cannot apply common operation to a batch of projects

### Steps to Reproduce

1. make a pyplug group by exporting a project as a group
2. make a proejct adding it in
3. go back to the project you exported the group from. make a change inside the group (not the params) and re-export, writing over the pyplug
4. go into your project that uses it its not updated

### Versions

* **Natron version/commit** 
2.1 dev 15 Jun 16
* **OS version:** 
osx 10.10.5

**Comment by MrKepzie** [comment]
I just tried to reproduce the bug without success. What I did:

- Create a graph Cherckerboard-->Blur-->Viewer
- Move the Blur into a Group so that the top-level graph becomes Checkerboard-->Group-->Viewer by using CTRL + G
- Pick the size parameter from the Blur and alias it on the group panel
- Export the Group to a Pyplug labeled TestPyPlug
- Close and restart Natron
- Make a project using CheckerBoard-->TestPyPlug-->Viewer
- Control the size parameter on the TestPyPlug and set it to a value different than 0. 
- Save project as TEST_PROJECT.ntp
- Make a new project (CTRL+N)
- Create an instance of TestPyPlug
- Go into the subgraph
- Click the lock button to unlock the Pyplug
- Add a ramp node in the graph before the Blur so that the group becomes Input-->Ramp-->Blur-->Output
- Adjust the ramp and change its colors (optional)
- Pick some random parameters from the Ramp and expose it on the group node (such as the point0 point1 and color0 color1)
- Re-export TestPyPlug and overwrite the existing one
- Close and restart Natron
- Reload TEST_PROJECT.ntp, and see the updated PyPlug

Repeat the steps but when re-exporting increment the version of the PyPlug to 2, you will see that Natron asks whether you want to update the PyPlug or not in your graph

**Comment by nicholascarroll** [comment]
I followed your steps and that works fine but I will test a little more on some variants to make sure it is robust, before closing this.

**Comment by MrKepzie** [comment]
Can you test on a more recent snapshot and see if you can reproduce ?

**Comment by nicholascarroll** [comment]
OK

**Comment by nicholascarroll** [comment]
Seems to be all working fine as of 28 June snapshot.

**Comment by MrKepzie** [comment]
Ok great

**Comment by MrKepzie** [comment]
We will release 2.1 soon
