### ISSUE TITLE
Expose ffmpeg command line options

### ISSUE THREAD

**Issue by bonalex01** [MrKepzie/Natron#1364]
FEATURE REQUEST Low priority!!!!

As some of the outputs are managed through FFMPEG I was wondering if we could gain access to the command line.
This would allow users to test/publish settings without asking YOU to constantly add this and that CODEC. 

(I wanted to make some tests with H265 4:4:4 10bit as a replacement for dpx)

**Comment by devernay** [comment]
I already though about that, but the command-line parser is not in the ffmpeg libraries, so a lot of code has to be copied from ffmpeg. And as with all ffmpeg code, there is little to no documentation.
Note that we actually provide the ffmpeg executable with Natron (does not work on Mac yet, though)

**Comment by devernay** [comment]
Note that 10 bits H264 (and probably H265) may not be available soon, because the x264 library has to be compiled either in 8bits or 10bits mode, so that a compiled ffmpeg can either produce H264 8 bits or 10 bits, but not both.
Why not use prores or dnxhd? these formats are very well supported by natron.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#161
