### ISSUE TITLE
Switch Node: Blocked Processing from other filter nodes.

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1380]
I am working on a tutorial for the Switch node and its automatic feature for NatronNation members. I have split one of my videos into three parts for random processing to explain how the Switch use demonstrate the continuous processing without having to render multiple projects back to your NLE.

The next three images are in the order that is supposed to be processed via the Switch inputs 0-2.
![switch 1](https://cloud.githubusercontent.com/assets/7956901/16397318/a357cd54-3c91-11e6-8291-5f97a1cfb213.png)

![switch 2](https://cloud.githubusercontent.com/assets/7956901/16397319/a640bec2-3c91-11e6-8923-89a819ceb19c.png)

![switch 3](https://cloud.githubusercontent.com/assets/7956901/16397322/a918176c-3c91-11e6-8346-a772b02a4c2a.png)

One the first input I have a DirBlur node at the end of the processing pipe before input 0. When it is enabled, the next two inputs (1-2) are not passed along. The next image is the display when the Dirblur node is active.

![switchnonpass_dirblur_enabled](https://cloud.githubusercontent.com/assets/7956901/16397363/ffe3a156-3c91-11e6-9918-8464a25eaf8c.png)

This next image is when the Dirblur is disabled.
![switchpass_dirblur_disabled](https://cloud.githubusercontent.com/assets/7956901/16397390/22faa8ce-3c92-11e6-8770-c2a8db07984f.png)

I thought it might be just the DirBlur node, but Angle Blur, Fill, God Rays are some of the nodes that block the passing off footage to the next Switch node inputs. So far these are the only nodes that I have text in Natron 2.0.5 and the Master beta snapshot that were giving me problems.

**Comment by devernay** [comment]
@MrKepzie the bug is probably this:

 when an effect is passthrough/identity, its framerange is set to the framerange above, which is wrong.

try a checkerboard->framerange(10,20)->switch->viewer graph

when between frames 10-20, the frame range in the "info" panel of the switch node is 1-1 for the input, but 10-20 for its output, which is wrong (both should be 10-20).

The GetTimeDomain action should always be called, even if the effect is passthrough.

**Comment by devernay** [comment]
OK we just found the bug.
