### ISSUE TITLE
Feature Request: Cryptomatte implementation

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1399]
A Natron implementation of Cryptomatte would be nice.
Cryptomatte is a tool created at Psyop by Jonah Friedman and Andy Jones. It creates ID mattes automatically with support for motion blur, transparency, and depth of field, using organizational information already available at render time. 

https://github.com/Psyop/Cryptomatte

Demo video: https://vimeo.com/136954966

Blenderartists thread: 
https://blenderartists.org/forum/showthread.php?402502-Cryptomatte-1-0-released!

**Comment by MrKepzie** [comment]
Seems cool, although do you know any renderer besides Arnold that can produce such files ?

**Comment by PostPollux** [comment]
No, I don't know any other renderers. Well, concerning the blenderartists thread, Lukas Stöckner has already written a working patch for Cycles. But of course this is not a official release.
Maybe other renderengines will adopt it, I don't know. I'mean it's just been released 8 days ago.

I just thought it looks like a very interesting and promising project. Due to the few renderers supporting it it's of course a low priority feature request. But nevertheless I think it's something to keep in mind. The more third party software adopt Cryptomatte, the faster it will grow...

**Comment by MrKepzie** [comment]
Anyway it's pretty straightforward to port for Natron, anybody with a bit of experience of the Python API can do this. One could even make a OpenFX for that

**Comment by jonahfriedman** [comment]
Hi, this is Jonah Friedman, co-author of Cryptomatte. Very excited to see this on the 3.0 milestone for Natron! Andy and I don't use a lot of Natron ourselves, but a Natron plugin is something that we'd definitely take an active interest in. Anyway, please consider us a resource for any questions about implementation details or the Nuke plugin. You can contact us to ask questions directly, or point us to whereever the details are being discussed and we can participate in that.

**Comment by MrKepzie** [comment]
Hi Jonah, 

Frankly this is not very hard to port the Nuke Gizmo to our PyPlug format, this is like a 3-hour work. The problem is that I'm not aware of a open-source software that can produce such images *yet*! It would be nice to have it released in Cycles at the same time that we launch a plug-in for that so that it increases the momentum on it and also gather eyes on 2 open-source solutions.

**Comment by rasamaya** [comment]
Yes! Cycles and Natron Cryptomatte support would be amazing!!
Have you had a chance to port the nuke Gizmo? I can take a crack at it next week, but it would take me much longer than three hours.

**Comment by PostPollux** [comment]
According to this post the cryptomatte implementation of Cycles will be in Lucas next experimental build:
https://blenderartists.org/forum/showthread.php?395313-Experimental-2-77-Cycles-Denoising-build&p=3143116&viewfull=1#post3143116

**Comment by skwerner** [comment]
I am interested in picking up the task of implementing Cryptomatte output for Cycles. In order to verify correctness, it would of course be extremely helpful to have a Natron node to extract the mattes MrKepzie, has there any work been done on this yet? I tried implementing my own Crypomatte node based on the OFX SDK samples, but am progressing very slowly due to my lack of experience with the OFX API.

**Comment by MrKepzie** [comment]
I unfortunately don't have time for this. 


One has to port all the Python functions in https://github.com/Psyop/Cryptomatte/blob/master/nuke/cryptomatte_utilities.py
to Natron's python API and make a PyPlug instead of the Nuke Gizmo and that's pretty much it.

**Comment by acjones** [comment]
Just a heads-up, we released a natron branch of Cryptomatte in Psyop's github.  

https://github.com/Psyop/Cryptomatte/tree/natron  

It's still a little buggy and may have some persistence issues due to some weird things that seem to happen with image channels and expressions.

The biggest limitation I hit is that there's no embedded metadata stream, so if you want to get all the features, you have to paste the manifest json text into a text input.

**Comment by MrKepzie** [comment]
Hi, 
Thank you for porting it to Natron. We can definitely help regarding the issues there may be with channels/expressions.

Note that Natron 3 is almost out for testing, bringing a new (easier and faster) expression language and a new PyPlug format (it's all in YAML now). There will be an utility shipped with Natron to automatically convert older files, and Natron 3 will still be able to load python-based PyPlugs and then can be re-exported to the newer format.

Regarding metadatas: this has been a feature request and was planned to be incorporated once Natron 3 becomes stable.

**Comment by aTanguay** [comment]
Can you elaborate on how to do this?

_"paste the manifest json text into a text input."_

I've got everything installed, mostly working, and I'm trying to get a matte out, but I think I need to do this, but it's over my head. Thanks for writing this. It would be REALLY helpful.

**Comment by acjones** [comment]
Hi Andy,

It's been a little while since I've looked at this, but basically you would click on the button to view the exr metadata, find the key called "cryptomatte/<some_characters>/manifest" and copy the text for the value of that key into the manifest input on the Cryptomatte node.  The text you copy would need to be valid json, so watch out for any bogus characters that might creep in during the process of copy/pasting.  For example, a rogue quote (") character could mess it up.

Hope that's helpful.  I would also caution that I don't have a ton of time to do much support for this plugin, and I was hoping it would just be a proof of concept to get a "real" version going for Natron 3.  I would definitely suggest saving your script, closing and re-opening to validate whether the persistence issues I was seeing are still there before you invest too much time using this in a production comp.

If anyone is using this significantly, and has made any improvements, we'd certainly welcome a pull request to the Cryptomatte repo.

**Comment by aTanguay** [comment]
Thanks AC. I think I found mine ... cryptomatte/f834d0a/name: "crypto_object"
That would get pasted into the 'Layer Selection' area or the 'Alpha Script' area?

Sorry for my ignorance, I'm just a user with just enough knowledge to mess things up. Hopefully it'll pick up some steam...I think more people are finally discovering how useful these Cryptomattes can be.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#163

**Comment by adamearle** [comment]
Have you guys seen this Id matts from blender, buuuuuuuut will it really work I haven't used tested it fully yet

https://www.youtube.com/watch?v=FrPC6nkv7L0
