### ISSUE TITLE
Frischluft node disconnect

### ISSUE THREAD

**Issue by Phantom-Studio** [MrKepzie/Natron#1414]
### Problem

When using Frischluft Deph of field (ofx plugin, http://www.frischluft.com/lenscare/, demo aivalable here) i have several issue :
A-natron pop up an error diallog when i plug an custom image in the iris input (for a custom bokeh) , telling me it must be the same format of the project (), wich i dont want (too cpu itensive).in general 256*256 or 512*512 is enough.
This not a frischluft issue since it is working correctly with other OFX capapble compositor.

B-when i re open a natron script, the input of the frischluft is always deconnected.

### Steps to Reproduce

A-connect a constant (256px*256px in iris input)

B-comp with a Frischluft node , save, quit , re open , and magic , it is disconnected

### Versions

Natron 2.1.2 (but also with previous version)64bits
Win7

**Comment by devernay** [comment]
probably an issue with [kOfxImageEffectPropSupportsMultiResolution](http://openfx.sourceforge.net/Documentation/1.4/ofxProgrammingReference.html#kOfxImageEffectPropSupportsMultiResolution)

Frishluft DoF probaby announces that it doesn't support images of different resolutions, whereas it does. Natron should probably just issue a warning for this (and for other kOfxImageEffectPropSupports* props) rather than forbidding these connections. The effect render should fail anyway if the effect really does not support it.

**Comment by MrKepzie** [comment]
It flags that it does not support multi-resolution. 
If you connect an iris with the same size as the source that's ok, otherwise it fails. We can just print a warning when loading a project
