### ISSUE TITLE
Transform overlay displayed on all viewers

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1424]
### Problem

Transform overlay appears on all viewers but its only connected to one.

**Expected behavior:**
Only show the overlay on viewers downstream from the transform node.

**Actual behavior:** 
All transform overlays show up on all viewers connected or not.

### Steps to Reproduce

1. add a read or constant
2. add a transform to it
3. connect to viewer1
4. add a new pane
5. add a new viewer2 to it
6. even  though viewer2 not connected to the transform, the overlay is on it

### Versions
natron 2.1.2 snapshot 20 aug
osx

**Comment by MrKepzie** [comment]
Overlays are drawn on all viewers currently.

**Comment by sozap** [comment]
I found it ok like this... Sometime you can create a node like a roto, and even if it's not connected it show up in the viewer, I found that convenient. I don't know how that behave in nuke... 
I guess having both behaviour as an option make things a bit complicated for nothing.

**Comment by nicholascarroll** [comment]
@sozap roto is different. and never mind nuke - rather what is the logic of having the controls to adjust a transform on a viewer that is showing a different image on a different node tree?

### Use Case
Load up four readers and do a scale of each. Per screenie. This bug is putting all four transform overlay controls on all four viewers which does not help. 
<img width="1280" alt="screen shot 2016-09-07 at 4 59 57 am" src="https://cloud.githubusercontent.com/assets/1062708/18286850/f8b327fe-74b7-11e6-9cde-c652ed03e927.png">

**Comment by sozap** [comment]
lol nice screenshot !

I may not fully understand your point because I don't work like that. I always have one big viewer on a secondary monitor. Sometime two but that's very special cases . Even when working with multiples sources. Also , I don't open many nodes properties , for transforms it's not more than two. Otherwise it gets confusing and I always try to do one thing at a time.

Your screenshot show clearly your point, put that's not a true use case... That said, different people have different workflows, it's nice that the software is able to adapt to everyone, not the opposite.

**Comment by MrKepzie** [comment]
Implemented in 2.2
