### ISSUE TITLE
Glow Node Errors

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1427]
The glow node is causing major issues in the latest snapshot (Natron-201609091113-22dada19a636f5ecb7ab7ca6b9cb2035e902a91c). When you add the glow node to a stream, it disconnects the pipeline and throws an error. See an attached image for reference.

![glow node error](https://cloud.githubusercontent.com/assets/7956901/18408676/f017a630-7703-11e6-9b5c-2b411e50792a.png)

**Comment by MrKepzie** [comment]
Rather than this, just regenerate all bundled PyPlugs
On 10 Sep 2016, at 20:18, Ole-André Rodlie <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1427<https://github.com/MrKepzie/Natron/issues/1427> via 6d9fc15<https://github.com/MrKepzie/Natron/commit/6d9fc153f628207a1b050f7f1d95f0a50c05336a>.
