### ISSUE TITLE
Inadvertant Unpremultiply on Invert after Roto

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1428]
### Problem

When adding an *Invert* node after a *Roto*, the *Invert* node's *Unpremultiply* option is active, even thought the *Roto* node's *Premultiply* option is off.

**Expected behavior:**
Leave *Unpremultiply* off

**Actual behavior:**
 *Unpremultiply* was on

### Steps to Reproduce

1. Add a read node and make sure *Output Premult* = Opaque
2. Append a Roto node and make sure *Premultiply* = false
3. Append an Invert
You will see the Invert's *Unpremultiply* = true

### Screenshot
![invert from 2016-09-10 20-39-37](https://cloud.githubusercontent.com/assets/1062708/18409890/b892361a-7796-11e6-94d4-b738fa9ecc4a.png)

### Versions
natron 2.1.2 21 aug snapshot
ubuntu 16.04

**Comment by MrKepzie** [comment]
Internally the Roto is implemented with a node tree, the last node being a Merge node. We could in a future version even allow seeing the internal node tree of the Roto group but for now nodes are not positioned correctly in the graph, they are just connected and stacked up one onto another.

In Nuke it looks like the premultiply option multiplies the inputs by the shapes before executing the Rotopaint tree on it. So it looks like they render twice:
1) Once the alpha mask of the shapes and they premultiply the input with it
2) Second render they take in input the output of 1) and apply the same tree again

In Natron currently the tree goes like this (assuming 1 item in the tree):

Input --> RotoShapeRender ->Merge (A: RotoShapeRender, B: Input) --> Premult 

Since the premult node always output premultiplied data that forces the flag to premult.
Maybe we should fix the output premult flag by making it unpremult if the Premult is disabled or premult if it is enabled.

**Comment by MrKepzie** [comment]
It's fixed for 2.2. Before that it's not possible.
