### ISSUE TITLE
Distributing community packages (ebuild/pkgbuild): copyright issues?

### ISSUE THREAD

**Issue by triceratops1** [MrKepzie/Natron#1489]
what copyright issues would i have if i provide community packages for natron (ebuild or pkgbuild)

**Comment by olear** [comment]
Depends. If you build from source (recommended) then everything is GPL2. If you plan to re-distribute/re-package the official binaries then you are in a gray zone, since we include some proprietary components (You are not allowed to distribute bin/Natron and bin/NatronRenderer). You will also need to distribute (make available) sources (LGPL/GPL) used to build the official binaries (http://downloads.natron.fr/Third_Party_Sources/).

Also note that Arch already have packages (from source) in AUR.

**Comment by devernay** [comment]
Note the binaries that @olear is talking about (bin/Natron and bin/NatronRenderer) are not those you can build from sources: these are binaries that handle crash reporting. If you build from source, you get everything except crash reporting, and Natron, openfx-io and openfx-misc are all GPL.

**Comment by triceratops1** [comment]
@devernay what copyright issues would i get with these "taboo"  binaries

my plan is simmilar to firefox-aurora packages    (/opt bundle)

**Comment by olear** [comment]
They are proprietary, so the package will taint the rest of the system and must be marked as "nonfree". Just remove bin/Natron and bin/NatronRenderer and rename bin/Natron-bin => bin/Natron and bin/NatronRenderer-bin => bin/NatronRenderer. 

But I highly recommend you make a proper package and build from source (this is Gentoo after all ;) ).

**Comment by triceratops1** [comment]
@olear  simmilar to ffmpeg-full (aur)
its legal share code

but its taboo share binaries

**Comment by olear** [comment]
Do what you want :) , just make sure to mark the package as nonfree (or similar). Btw, last time I checked AUR had a Natron-binary package (I may be mistaken).

**Comment by triceratops1** [comment]
@olear https://aur.archlinux.org/packages/ffmpeg-full/  

 GPL3, custom:unredistributable 


would be fine?

**Comment by olear** [comment]
Yes. Just replace GPL3 with GPL2.
