### ISSUE TITLE
Node Graph: hints - link between nodes

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1500]
Can we get a preference option to be able to deactivate the need to hold down the control or command keys just to connect a single or a group of nodes to a pipeline in Natron 2.2? I understand that some may have had issues with the workflow before, but I didn't have a problem with it. It feels like an extra step in my personal workflow.

**Comment by CameraRick** [comment]
This was made because of my suggestion posted here: https://github.com/MrKepzie/Natron/issues/1488
The comments regarding this issue are here (some confusion went on): https://github.com/MrKepzie/Natron/issues/1487

My reasoning behind this is that the hints are WAY too aggressive as they were. See this crude example here: https://youtu.be/rX1brSEThyE
Imagine I just want to connect the Blur to the dot. Even if I have connected the blur manually, I can't even position it next to the PIK without it getting a hint to something I don't want to connect to.

As I also mentioned in my initial suggestion, I think there could be different approaches to this.
Like pressing a button if I don't want hints, or something like only giving hints for main-inputs (InM etc shouldn't pull a hint for me).
Usually I prefer no hints at all, but dropping a node on an existing pipe to get it in, like it would behave in Nuke; as this is only managable with Hints in Natron, I hope there is a way how every user might be moderately happy :)

**Comment by MrKepzie** [comment]
I think there could be a way where we automatically enabled hints if nearby a single edge, but if more are present it requires holding CTRL

**Comment by blackearth2014** [comment]
MrKepzie,

I like that idea.

**Comment by CameraRick** [comment]
Looking at the Demo scripts (Big Hero 6 etc), those were build really tight. I don't know if that is imtended in Natron, so I'd be really curious how 'far' this would reach?
I personally don't see a reason for the aggressive hints with Inputs at all tbh, only for hints towards existing pipes

**Comment by MrKepzie** [comment]
But even on existing pipes this can be aggressive if you are in the middle of a mess. The only clean way is to have no ambiguity, meaning only 1 connection is clearly going to happen nearby, if not do not even attempt to show any hint.

**Comment by CameraRick** [comment]
In the middle of a mess, everything is a mess :)

In Nuke, it connects as soon as the Cursor Hits the Pipe underneath which Works quite well in most scenarios.
Having only one hint happen is the way it Works now, no? One for in one for out, would be strange if it only connecten the In but no out?

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#175
