### ISSUE TITLE
wrong formatted render times

### ISSUE THREAD

**Issue by PostPollux** [MrKepzie/Natron#1529]
### Problem

The "Time remaining" Tab of the render progress shows things like:
1h 98 min     or    2h 187 min
  
![bildschirmfoto_2016-12-10_12-36-07](https://cloud.githubusercontent.com/assets/9008901/21073046/5a255de2-bed5-11e6-90d4-1a8b0189f1c7.png)

**Expected behavior:** [What you expected to happen]
I think the minutes shouldn't go higher than 59 ;)

### Steps to Reproduce

1. Render a heavy project

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
Natron 2.1.9 Release

* **OS version:** 
Linux Manjaro

**Comment by MrKepzie** [comment]
It should be fixed in https://github.com/MrKepzie/Natron/commit/97a9b655b0126f2dbbb1e597cf5c5ecef94a7e9b

**Comment by marcdraco** [comment]
Ah! Good to know this is squashed - but if these are marked as closed it's harder (for us noobs) to find them if we're using the most recent release and not a nightly (if that's the correct term).

Can we have some guidance how best to deal with these so we don't duplicate work? I know we can use search but it's hard to second guess how the problem we're having might be described, if that makes sense.

**Comment by devernay** [comment]
just remove the "is:open" in the filter when searching for issues

**Comment by marcdraco** [comment]
File that under "d'oh!"

I hate that we're making more work for the devs. by missing this sort of thing. I get the impression Git is not really that helpful for non-developers as it seems to erect more barriers than it solves. This is troubling with excellent open source like Natron because people in the amateur and semi-professional end business want to see it succeed. I intend to do some tutorials to help people out in future and raise awareness because it's really off the radar for a lot of us - I only discovered it by chance!
