### ISSUE TITLE
Features wanted: Vectorscope and Waveform

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#154]
As in broadcast tools.
Helps a lot for color grading/matching.
Waveform could be horizontal or vertical.

**Comment by mash-graz** [comment]
this is a very old feature request, but it's still missing for daily work.
color related corrections do make much sens without useful measurements.

**Comment by sobotka** [comment]
@mash-graz A vectorscope is extremely challenging to code in the modern era as it requires knowing the chromaticity of the encoded YCbCr stream, and even then, it would take a good deal of thought as to how to implement a fully colour managed solution via OCIO. RGB data as well would require being chromaticity aware to locate the data in relation to the RGB positions on the scope.

A waveform is equally challenging. Is the data scene referred or display referred? Are broadcast levels markings correct given the sources? Etc.

So while both of these things are rather trivial to implement incorrectly, which would break and be misleading for a huge chunk of contexts, they are *extremely* challenging to implement correctly across all of the ingestion media.

**Comment by mash-graz** [comment]
yes -- i have to agree! :)

i studied the code of the actual histogram implementation in natron and -- like often, when i try to understand the code of natron -- i was really impressed. it's far beyond the level of programming i'm able to do myself. but i'm still very interested in this specific feature, because i'm using nuke and natron quite often to analyze video material and do some color related development (e.g.my [ACES profiles for the GH4 video profiles](http://users.mur.at/ms/git/gitweb/?p=OpenColorIO-Configs.git;a=summary)).

OCIO support and integration into the natron viewer would be the most desirable solution, but i could also accept a more simple openFX node, which has to be chained after an OCIO transformation node. a solution, which just transforms an incoming rec709/linear RGB picture to a waveform/vectorscope image. but it has to be really fast an efficent, otherwise it does not make much sense. compute shaders to gather the data and vertex +  fragment shades for the final drawing to frame buffers look like the most promising way to archive this goal.

but i'm still very confused, how this kind of OpenGL usage should be implemented in a natron extension in the most efficient and compatible way? i did take a look into the shadertoy and OpenGL / osmesa examples in the test section of openfx-misc, but it's a burdensome challenge to grasp this topics...

**Comment by MrKepzie** [comment]
On OpenFX side (plug-ins) we use osmesa to implement OpenGL plug-ins. 
Basically, with osmesa we can have the same code that does CPU rendering and GPU rendering using the same OpenGL calls. When running on CPU, shaders are compiled with llvm and very efficient. 

Currently Natron, does not support OpenGL plug-in renders, hence OpenFX plug-ins will always receive images on the CPU before rendering and will have to render back to the CPU.
In the next version (2.2) Natron will support OpenGL, meaning that portions of the rendering tree will be executed entirely on the GPU (the plug-in will receive textures and not images).

**Comment by mash-graz** [comment]
thanks a lot for this lightening answer concerning the natron OpenGL jungle!

**Comment by marcdraco** [comment]
Did we progress any more on this? The histogram is very useful but as I think Omar would note, you really can't beat a decent vectorscope for getting things like fleshtones right. I expect Omar and others can do it without that but hacks like me (who are borderline colourblind) totally rely on them. It's said (not that I've tried it) you can colour correct bad footage on a worse monitor just using the scope!

**Comment by neilpho** [comment]
I'd like to vote for this! Waveform, RGB parade, and vectorscope tools are seem much better than a histogram. I guess the histogram was just the first thing people thought of and then it tuck around.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#79
