### ISSUE TITLE
Merge node preview/final render results different

### ISSUE THREAD

**Issue by nialv7** [MrKepzie/Natron#1557]
### Problem
The result showed in preview window and the final rendering is very different.

Writer & Viewer is using the same source.

Merge node properties:
![Merge node properties](http://i.imgur.com/56bwTd2.png)

Preview:
![Preview](http://i.imgur.com/Cpp53w0.png)

Final Render:
![Final Render](http://i.imgur.com/Wc7Xr9N.png)

### Versions

* **Natron version/commit** Natron version 2.1.9 Devel.

**Comment by spartacruz** [comment]
Could you provide your nodes-capture? Maybe I (or someone else) can help

**Comment by nialv7** [comment]
@spartacruz Here:
![](http://i.imgur.com/nwfxcy6.png)

The second branch of the switch node is not relevant.

**Comment by devernay** [comment]
alpha=0 on the background. Enable the checkerboard in the viewer to verify this.
why did you set alpha=0 on B?

**Comment by nialv7** [comment]
@devernay What do you mean? B doesn't have an alpha channel.

**Comment by nialv7** [comment]
@devernay Viewer with checkboard:
![](http://i.imgur.com/rAkCahw.png)

**Comment by devernay** [comment]
add an alpha channel to i032.png, just check the A box.

From the Merge node documentation (I spent more than one week fixing the doc, please read it):

"Note that if an input with only RGB components is connected to A or B, its alpha channel is considered to be transparent (zero) by default, and the “A” checkbox for the given input is automatically unchecked, unless it is set explicitely by the user. In fact, most of the time, RGB images without an alpha channel are only used as background images in the B input, and should be considered as transparent, since they should not occlude anything. That way, the alpha channel on output only contains the opacity of elements that are merged with this background. In some rare cases, though, one may want the RGB image to actually be opaque, and can check the “A” checkbox for the given input to do so."

**Comment by nialv7** [comment]
@devernay I see. But I think this is still kind of a bug though. It's really confusing to get different result from the Viewer and the Writer. And it's hard to tell what went wrong (turning on the checkboard in Viewer doesn't help) without digging into the documents.

**Comment by devernay** [comment]
why did you connect the mask input for the Merge node? It shouldn't be needed. Mask is to apply the effect on only part of the image, which is *not* what you want. You want to Merge A over B, that's all. No mask.

**Comment by nialv7** [comment]
@devernay I connected the mask as a workaround: Using the alpha of A as a mask, and the result is what I wanted. The mask input is not related to this bug report.

**Comment by spartacruz** [comment]
@nialv7 Ahh I see what you mean. Final render is what you wanted, but the preview show it different.

I also wonder why it happen...

**Comment by devernay** [comment]
This is definitely a misuse of the mask input to the merge node (your foreground becomes transparent, see the viewer with the checkerboard on). You should think twice before doing that, because you are producing a wrong image (think about what "alpha" means).
I cannot reproduce the white background, though. Can you upload the project + the images + your render somewhere, and post or send me a link (support@natron.fr)?

**Comment by spartacruz** [comment]
please send me too (cetecicu@icloud.com)
Want to try on different suite.

**Comment by nialv7** [comment]
@devernay After I removed the mask input, the checkboard showed up corrected... Guess it's my fault all along.

So the only problem is just that the checkboard is not showing up even when mask input is not used (but connected) in the merge node.

**Comment by devernay** [comment]
by "mask input is not used (but connected)", you mean it's connected in the graph but the checkbox is not checked?

I get the same result as if it were not connected when I uncheck the checkbox.

If you observe something different, then it's a bug, please send me a project showing that, because I cannot reproduce it.

**Comment by nialv7** [comment]
It's weird because now I can't reproduce it either. Guess I will just close this issue for now, and re-open if it comes back.
