### ISSUE TITLE
Natron integrated gegl request

### ISSUE THREAD

**Issue by vpaintanimation** [MrKepzie/Natron#1585]
natron can integrate gegl as a special effect tool set, if GPL compatible BSD, can also be integrated OpenCV

**Comment by devernay** [comment]
yes, we could integrate GEGL, libavfilter, frei0r, gstreamer, etc., but we probably won't, because we're missing a few brains and hands to produce the code.
Feel free to contribute, though!
there's already a G'MIC plugin somewhere, and a frei0r plugin would be easy to make also.
The proper repository to contribute these is https://github.com/NatronVFX/natron-plugins

**Comment by vpaintanimation** [comment]
I know that the development of special effects is not easy,Thank you for everything you have done
