### ISSUE TITLE
roto mask edge noise

### ISSUE THREAD

**Issue by Eneen** [MrKepzie/Natron#1594]
Please take a look @ screenshot:
![natron_roto_mask_bug](https://cloud.githubusercontent.com/assets/25537418/24606939/cede221a-186f-11e7-8d39-976651269897.jpeg)
I seems some kind of noise is added to bezier roto, but I think this is case when there should be nicely anti aliased straight edge.

Natron V. 2.2.5, Windows 10.

**Comment by MrKepzie** [comment]
You need to set the Feather parameter to at least 1.5 px

**Comment by Eneen** [comment]
It is 1.5px...

**Comment by MrKepzie** [comment]
Can you show the settings of the Roto node itself and the alpha mask in the viewer directly ?

**Comment by Eneen** [comment]
Sure, here you go:
![natron_roto_mask_bug2](https://cloud.githubusercontent.com/assets/25537418/24609119/c9195912-1879-11e7-9913-66f1de1d937e.jpeg)

**Comment by MrKepzie** [comment]
Fixed by https://github.com/MrKepzie/Natron/commit/49981cc8964c3c14d8f9aa8f3ed2c14ca7c5751b

Note that there are still a few minor artifacts that are due to a bug in the cairo library.

In Natron 3.0 we moved away from cairo anyway and the Roto is fully implemented in OpenGL (GPU accelerated)  so all these artefacts should no longer be an issue.

**Comment by Eneen** [comment]
Thx alot! I can also try to report bug to cairo but I need info what to report.

**Comment by MrKepzie** [comment]
I did not investigate further but it seems that the rasterisation of coons patch with very sharp angles produces artifacts. 
Anyway I can't spend more time on this since we don't use it anymore as of Natron 3
