### ISSUE TITLE
Natron doesn't seem to display the name of AOV's in EXR's properly...

### ISSUE THREAD

**Issue by mangopipeline** [MrKepzie/Natron#1603]
### Problem
load the following .exr in natron, and notice that names for the xtra AOV channels is just displayed as partX.color.rgb instead of 

**Expected behavior:** [What you expected to happen]
Natron should display the names properly like VRayDiffuseFilter

**Actual behavior:** [What actually happened]
Natron displays the name of VRayDiffuseFilter as Part1.color.rgb

### Steps to Reproduce

1. load the attached .exr in a read node
2. click on the channel drop down to see the available channels.

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions
2.26

* **OS version:** 
windows 10
![exr channel problem with natron](https://cloud.githubusercontent.com/assets/5678056/25118365/a46fd1d2-23db-11e7-806b-89382eaa685b.png)

could not attached the exr so you can get it from here...
https://drive.google.com/open?id=0B3Irm8-2LgJsZU1qRFJsUl9KMkk

**Comment by MrKepzie** [comment]
In OpenEXR2 they added a "name" meta-data to name layers instead of using the regular per-channel naming. Until now we only used channel names. Since they are all R,G,B,A for each individual layer of your file, each part is named in a generic way (i.e: part0, part1, etc...)
I patched the ReadOIIO plug-in so that it checks for a "name" meta-data and name the layer accordingly if present.

**Comment by MrKepzie** [comment]
Fixed in https://github.com/MrKepzie/openfx-io/commit/d6b72f8e393df39e648793574ee668a5eaf113b6

**Comment by mangopipeline** [comment]
Awesome you rock thanks!
