### ISSUE TITLE
h264 issues on windows

### ISSUE THREAD

**Issue by mangopipeline** [MrKepzie/Natron#1608]
### Problem
Setting a write node to render .mov files using h264 creates files that quicktime and other apps are not able to open.

### Steps to Reproduce

1. Open the attached file
2. Hit render on write node 2
3. Notice the write node error
4. change the write node format to 1920 by 1080.
5. hit render again
6. try to view the rendered .mov

file did not attached so i'm share it in via google drive...
https://drive.google.com/open?id=0B3Irm8-2LgJscGlNOXpsQWJfaVE

### Versions
natron 2.2.6 release
windows 10

**Comment by MrKepzie** [comment]
We recently upgraded the ffmpeg version we ship with Natron and now support 10 bit encoding, we may have introduced a bug in the meantime. Can you check that 10 bit encoding actually works as a workaround ?

**Comment by mangopipeline** [comment]
Yeah no problem.
I'll let you know as soon as I get around to it :)
Later today more than likely

**Comment by mangopipeline** [comment]
I'm not having any luck with 10 bit encoding either...
for m h264 just either fails, or creates files are corrupted... :(

**Comment by MrKepzie** [comment]
I just fixed the issue in https://github.com/MrKepzie/openfx-io/commit/856fc4a1f7e92d0f172bf45d96742b20698f4481

The problem is a bug when you select Output format to "Input Format", in your case the bug makes the output image size not dividable by 2 and the encoder fails. This has been fixed and will be available in next snapshots. In the meantime, use another Output format option or crop yourself with the Reformat

**Comment by mangopipeline** [comment]
You ROOOOOOOCK!!!!
