### ISSUE TITLE
SVG does not render properly

### ISSUE THREAD

**Issue by tebicap** [MrKepzie/Natron#1629]
### Problem

SVG (shadows) does not render properly when it's MERGEd (OVER) with any B input with alfa chanel unchecked, while it's displayed well in the visor.

here captures: https://drive.google.com/drive/folders/0ByzCdzO0jRwGbmVIbG5LWXZTbG8?usp=sharing

### Versions

Natron version 2.2.8 Release.
Ubuntu 17.04 - 64 bits
GeForce GT 610/PCIe/SSE2

**Comment by devernay** [comment]
I think this is normal: you marked the input to Write as "premultiplied", so Natron unpremultiplies it before writing. Since you unchecked alpha on B, alpha is zero almost everywhere, except in the "shadow", where the unpremultiplied value is white.
You can easily check this by clicking on the checkerboard icon in the viewer.

You probably want B to have an alpha of 1 everywhere and check  the A channel on B.

Another (dirty) solution would be to set the input premult in the writer to "opaque" (which means to consider everything has an alpha of 1)

**Comment by devernay** [comment]
I got a thumb up from @tebicap, so I guess the issue is fixed
