### ISSUE TITLE
Build Instructions for Windows are Not Clear

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#1640]
The [build instructions for Windows](https://github.com/MrKepzie/Natron/blob/master/INSTALL_WINDOWS.md), are not clear. As a result I cannot build.

## Expected 
Expected for the instructions to be a series of steps that if followed correctly will get it installed.

## Actual
Actually, the instructions are too loosey goosey. They begin like this:

> Installing with MSYS2
> MSYS2 is a unix-like toolchain that can be used to build Windows applications. ...
> Clone the MINGW-packages repository:
> cd tools/Windows
> git clone https://github.com/MrKepzie/MINGW-packages

This has not told us whether we are to actually download and install MSYS2 yet. Where is the directory 'tools'? I did not see it. And git does not come with the base MSYS2 install.

> Set the environment variable MINGW_PACKAGES_PATH to the location of the MINGW-packagesdirectory.
> Using pacman, the MSYS2 package manager, install the following packages:

It would be alot easier if the pacman command was written there.

**Comment by nicholascarroll** [comment]
Specifically where I am stuck is trying to build the MINGW packages in https://github.com/MrKepzie/MINGW-packages. I tried makepkg-mingw for boost. It gave errors about not having Python3.

**Comment by MrKepzie** [comment]
Hi Nick,

Msys2 is a moving target and it's very hard to maintain build instruction for it, that's why the install instruction are outdated.
Sometimes the PKGBUILD file has to be modified: I modified everything using Python3 so it won't be required (boost and Pyside/shiboken).

To actually build a package, go in the directory and type:

    makepkg-mingw --skippgpcheck --noconfirm --skipchecksums -dLfC

To install it

    pacman --force --noconfirm -U mingw-w64-x86_64-<PACKAGE_NAME>

To build Natron you only need boost, Qt4, shiboken, pyside, and their dependencies. 
Other librairies are needed most likely for openfx-io plug-ins.

Then building is as simple as on linux, except that the qmake spec is:

    qmake  -r -spec win32-g++ CONFIG+=relwithdebinfo

Do not build with CONFIG+=debug, the on mingw has a bug and it can spend more than 15hours without successfully linking. The best you can do is relwithdebinfo.

Note that we use msys2 and g++ because it's the only free target that enables proper OpenMP on Windows: Visual studio doesn't support it well and the intel compiler is not free.

**Comment by nicholascarroll** [comment]
OK Thanks. I will try with those notes and document my steps and upload them here.
Cheers.

**Comment by devernay** [comment]
@MrKepzie maybe you could add your hints to the windows build instruction and close this issue?

**Comment by nicholascarroll** [comment]
It says install toolchain with pacman. But what command is that? If I install toolchain like this: 
`pacman -S --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain`
Then I will get gcc7. Or should it be gcc5?

**Comment by MrKepzie** [comment]
Once msys2 is installed, all the packages that are referenced from the official repo point to very cutting edge packages (such as gcc 7).

To avoid that, I suggest that you first install the basic toolchain with the command that you indicated, and in a second step, you go into the MrKepzie/MINGW-Packages/mingw-w64-gcc and you compile it manually with the commands I gave you in the previous message.

Once you have gcc 5 installed instead of the 7, you can build manually all packages required by Natron.

**Comment by nicholascarroll** [comment]
Getting an error on build of gcc5 in your repo
make[3]: *** [Makefile:1065: graphite-isl-ast-to-gimple.o] Error 1
So I am trying other ways to downgrade gcc. Will update here.

**Comment by nicholascarroll** [comment]
I tried by doing these steps:
1. Download msys2-x86_64-20161025.exe from http://www.msys2.org. Install it and at the end say "Yes" to launch it. It launches with a terminal prompt "MINGW64".
2. At the MINGW64 prompt enter:
3. Reopen MINGW64. You can find it in the Windows menu as "MSYS2 MingW64bit" 
4. enter "pacman -Su", to make sure it has updated everything. When it has, it will say "nothing to do".
5. Download http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-libs-5.2.0-1-any.pkg.tar.xz
6. $ pacman --force --noconfirm -U mingw-w64-x86_64-gcc-libs-5.2.0-1-any.pkg.tar.xz
7. Download http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-5.2.0-1-any.pkg.tar.xz
8. $ pacman --force --noconfirm -U mingw-w64-x86_64-gcc-5.2.0-1-any.pkg.tar.xz     
9. $ pacman -S make binutils patch patchutils tar diffutils pkg-config unzip bison rsync zip git python2 yasm 
10. $ ln -s /usr/bin/python2 /usr/bin/python 
11. $ pacman -S mingw64/mingw-w64-x86_64-gdb mingw64/mingw-w64-x86_64-cmake mingw-w64-x86_64-eigen3  mingw-w64-x86_64-libraw mingw-w64-x86_64-pango mingw-w64-x86_64-pangomm mingw-w64-x86_64-librsvg mingw-w64-x86_64-libzip
14. $ mkdir natron-build; cd natron-build
15. $ git clone https://github.com/MrKepzie/MINGW-packages
16. $ cd MINGW-packages/mingw-w64-boost
17. $ makepkg-mingw --skippgpcheck --noconfirm --skipchecksums -dLfC
At step 17 build failed with this error:

> In file included from ./boost/python/detail/prefix.hpp:13:0
>    from ./boost/python/numeric.hpp:8
>    from libs\python\src\numeric.cpp:6:
> ./boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
> compilation terminated.
> ...failed gcc.compile.c++ bin.v2\libs\python\build\gcc-mingw-5.2.0\release\address-model-64\pch-off\python-3.4\threading-multi\numeric.o...
> gcc.compile.c++ bin.v2\libs\python\build\gcc-mingw-5.2.0\release\address-model-64\pch-off\python-3.4\threading-multi\list.o

**Comment by nicholascarroll** [comment]
I guessed maybe you want me to use the python in your repository so I uninstalled python with `pacman -R python2'`and went into MINGW-packages/mingw-w64-python2 and ran  `makepkg-mingw --skippgpcheck --noconfirm --skipchecksums -dLfC` but that also gets an error:
 

> -L. -ltk86 -ltcl86 -ltk86 -ltcl86 -lws2_32 -lgdi32 -lcomctl32 -lcomdlg32 -limm32 -luuid -loleaut32 -lole32 -lpython2.7 -o build/lib.mingw-2.7/_tkinter.pyd
> error: [Error 3] The system cannot find the path specified: 'C:/Users/User/natron-build/MINGW-packages/mingw-w64-python2/src/Python-2.7.10/Modules/_ctypes/libffi/*.*'
> make: *** [Makefile:496: sharedmods] Error 1
> ==> ERROR: A failure occurred in build().
>     Aborting...

**Comment by MrKepzie** [comment]
You can download the latest boost package from pacman, or pick an already built older version like you did from repo.msys2.org. You don't have to build it yourself.

**Comment by nicholascarroll** [comment]
So I don't need to use anything from your package repository? But still need to use gcc 5?

**Comment by MrKepzie** [comment]
Basically yes, our packages just fix minor issues (namely in qt4 or shiboken/pyside) and ensure that we have trace of a stable version.

**Comment by nicholascarroll** [comment]
OK thanks.
