### ISSUE TITLE
PIKColor on natron 2.3 is inverted ?

### ISSUE THREAD

**Issue by groslaine** [MrKepzie/Natron#1641]
### Problem
PIKColor on natron 2.3 act differently than in other version (2.2.8 for example). I use the same setting and image but the result is completly different.

**Expected behavior:** 
![natron 2 2 8 pikcolor](https://user-images.githubusercontent.com/30377707/28497875-a90722c0-6f91-11e7-9582-6d52ce62c208.PNG)

**Actual behavior:** 
![natron 2 3 pikcolor](https://user-images.githubusercontent.com/30377707/28497878-afb51898-6f91-11e7-97cf-47cb9bcaf9b2.PNG)

### Steps to Reproduce

1. Read an image
2. Add the PIKColor
3. Compare the result

### Versions

* **Natron version 2.3
* **OS version:** Windows 10

**Comment by MrKepzie** [comment]
This bug was already reported and fixed in https://github.com/MrKepzie/Natron/issues/1637

Closing
On 23 Jul 2017, at 10:29, groslaine <notifications@github.com<mailto:notifications@github.com>> wrote:

Problem

PIKColor on natron 2.3 act differently than in other version (2.2.8 for example). I use the same setting and image but the result is completly different.

Expected behavior:
[natron 2 2 8 pikcolor]<https://user-images.githubusercontent.com/30377707/28497875-a90722c0-6f91-11e7-9582-6d52ce62c208.PNG>

Actual behavior:
[natron 2 3 pikcolor]<https://user-images.githubusercontent.com/30377707/28497878-afb51898-6f91-11e7-97cf-47cb9bcaf9b2.PNG>

Steps to Reproduce

  1.  Read an image
  2.  Add the PIKColor
  3.  Compare the result

Versions

  *   **Natron version 2.3
  *   OS version: Windows 10
