### ISSUE TITLE
[natron2.3.0 for win7_64]  The read node and the nuke OFX plug-in do not work properly

### ISSUE THREAD

**Issue by githob605608886** [MrKepzie/Natron#1644]
---------------------------
Denoise1
---------------------------
<p>Please position the analysis region over a flat area of the frame. Minimum region size is 80x80 pixels.Working at proxy scale will generate inaccurate result and is not recommended.</p>
---------------------------
OK   
---------------------------

### Problem:

1. all nuke OFX plug-ins are not normal, and some Denoise1 like problems occur. The "keylight" node showed noise.

2. "Read" node reads PNG and GIF normally, but TIFF, JPG, and PSD make mistakes

## Suggest:

"Roto" and "rotopaint Life Time" nodes like nuke can display in the interface parameters, the current version of life time I don't know how to increase the scope of numerical, and B-spline curve, not B-spline I couldn't picture mask

### Versions

* **Natron version 2.3 Release/commit** (Window): 
* **OS version: Win7 for 64 **

**Comment by devernay** [comment]
These plugins are not officially supported on Natron, neither by Foundry nor by us, and they are made to work with Nuke so they may use nuke-specific APIs. I don't even think the Nuke license allows the use of these plugins in another host.
Concerning reading images with the Read node, this was a build issue on windows, and should be fixed in the 2.3.1 binary.
