### ISSUE TITLE
2.3.1 i386 Debian crash 

### ISSUE THREAD

**Issue by marillat** [MrKepzie/Natron#1647]
Natron 2.3.1 architecture i386 Debian unstable

Natron crash at startup with openfx plugins. without Natron doesn't crash.

First I'm unable to build Natron with gcc 6.4.0 and 7.1.0 (a bug report is needed ?)
Here Natron is built with clang 3.8

I don't see this crash under an amd64 machine with virtualbox.
You can download i386 and amd64 packages from deb-multimedia.org repository.

Here is the full bt
https://gist.github.com/marillat/15d2a715d7138b5b53a9c2639d1f1463

**Comment by devernay** [comment]
We strongly recommend that Natron and the plugins be compiled with the same libraries/compiler, especially if the plugins use dynamic libraries. That shouldn't be much of an issue on Linux (as opposed to macOS), because Linux better handles symbol resolving with dynamic libraries, but this should be considered dangerous.

Did you try the pre-built packages from https://github.com/MrKepzie/Natron/issues/1651 ?

Can you tell us more about your compilation problems with gcc 6 and 7? We can probably work on fixing these.

**Comment by marillat** [comment]
natron and all plugins (opefx-io, openfx-misc) has been built with clang 3.8.

Pre-build package from #1651 are not installable because libgflags2v5 doesn't exist in Debian.

Also the debian build system files in debian/ from #1651 come from my work so I think these packages should also crash on i386 architecture.

A new issue need to be filed for build problems ?

**Comment by marillat** [comment]
This bug doesn't exist in 2.3.3

**Comment by devernay** [comment]
Closing. Note that the 2.3.3 binaries we produce are now compiles with GCC 7.2.0, and we compile Qt4 in C++11 mode (this requires two small patches).
