### ISSUE TITLE
Transform node math incorrect in viewer

### ISSUE THREAD

**Issue by troywilliams1** [MrKepzie/Natron#1649]
### Problem

When transforming an image that is read into the viewer, the resultant math seems incorrect in the viewer, for instance: loading an image of size 6000,3000 and transforming the scale at a defined center of 0:0, by a factor of 1.3653333 the result should show ~8192,~4096, however the result in the viewer will show 8200,4104. There is some random translate also being applied that results in math that appears even further off of what the user has input. The translate value will change when zooming in and zooming out in the viewer, when zooming out with the mouse wheel view the Center position, it will update by factors of 2.

**Expected behavior:** When applying transform math, the resultant math is correct in the viewer.

**Actual behavior:** When applying transform math, the resultant math is incorrect in the viewer.

### Steps to Reproduce

1. New project
2. Read new image any size
3. Attach transform
4. Connect to viewer
5. Set center position in transform node at 0,0
6. Set a scale value in the transform
7. Look at the viewer detail notice that the resultant math does not match.
8. Looking at the info tab of the transform node, the RoD data looks incorrect as well, albeit closer to truth

![image](https://user-images.githubusercontent.com/18218357/28728545-ad284716-738e-11e7-8a32-3368eae15a45.png)
![image](https://user-images.githubusercontent.com/18218357/28728559-b971b98a-738e-11e7-9e2d-31c8b225b2cc.png)

### Versions
Natron version 2.2.8 Release.
* **Natron version/commit** (they can be retrieved from the About Window): 
This software was compiled from the source code branch tags/2.2.2 at version 256ed31 using GNU C++ version 5.2.0 with OpenMP 4.0 targetting Intel x86-64 for Unix Environment.
The bundled openfx-io plugins were compiled from version 5f69331.
The bundled openfx-misc plugins were compiled from version f51c977.
The bundled openfx-arena plugins were compiled from version a731e9c.

* **OS version:** 
Windows 8.1 Enterprise 64bit
Intel i7-3820
Nvidia GTX760 382.53
32GB

**Comment by devernay** [comment]
You checked the "black outside" checkbox, which adds a one-pixel black and transparent border around the image. Since the size of one pixel depends on the zoom factor, the viewer RoD changes when you zoom in or out, and the changes occur at scales 50%, 25%, 12.5%, etc.
Uncheck "black outside" and that one-pixel border won't be added. The image size, though, will be rounded to the closest pixel.

Does that explain better what happens? Can I close the issue?

Note that if you want to transform the image data to a given size, rather than computing the scale manually, you should use the reformat node. It uses exactly the same resampling function, and it has the advantage of setting the "format" to the proper value, too.

**Comment by troywilliams1** [comment]
Good to know! I did not manually check 'on' the 'Black outside' box however. It appears that 'Black outside' is on by default when you create a transform node. Which produces some unexpected behavior in my personal opinion. Not sure if there was a reason to have 'Black outside' on by default upon creation.

**Comment by troywilliams1** [comment]
By the way, setting the option 'black outside' to disabled fixes the problem, I suppose the behavior just seems non-intuitive to me, given that it is on by default.
