### ISSUE TITLE
Should Merge consider RGB images have alpha=1 or alpha=1 (currently alpha=0): use case

### ISSUE THREAD

**Issue by marcchristopher** [MrKepzie/Natron#1660]
I have been a long-time Blender user and so far simply used the Blender compositor. Only recently, when a more complex setup was needed, I decided to try out Natron. And after a few hours of going back and forth I found what appears to me as a pretty weird bug...

### Problem

This could be pretty difficult to describe, so I created test files that illustrate the situation. You can download them here (550MB): http://kliq.at/NatronTest

In a nutshell: When compositing together two multi-layer EXR image sequences with a mask (specified by an ID pass, but that seems to be irrelevant for the bug), the output is correct, as long as no additional color adjustment is done. However, as soon as a `Color Correction` or a `Grade` node is added after the final `Merge`, the output only shows the `A` connection of the merge operation.

### Steps to Reproduce

To reproduce the bug...

1. Open Natron and set up a scene with resolution HD_720, frame range 1-48, 24fps (not that it would matter).
2. Add a `Read` node for the image sequence `natrontest_main##.exr`.
3. Add another `Read` node for the image sequence `natrontest_light##.exr`. Set the `Output Layer` to `Light.Combined.RGBA`.

To briefly explain what this is supposed to achieve: When rendering the scene (in Blender/Cycles) normally, the scene contains a lot of fire flies, so I activated "Clamp Indirect" to make rendering more efficient. The `main` sequence contains the EXR files for this setup. Unfortunately, this had the unwanted side effect of darkening the light source. Which is why I created a separate render layer containing just that light source without any clamping, but a higher number of samples. This is contained in the `light` sequence.

Now, to composite these image sequences back together...

4. Set up the usual node tree to composite the diffuse and the glossy channels of the `main` sequence together. (I did this, as I wanted to be able to denoise separate channels.)
5. Create another Merge (over) node, connecting the composite of the `main` sequence in input `B` and the `light` sequence in input `A`.
6. Duplicate the `Read` node containing the `light` sequence and set the `Output Layer` to `Light.IndexOB.X`.
7. To get exactly the ID mask for the light source, add a `ZMask` node and set the `Center Value` to 2. (In this simple setup this is not really necessary, but my original scene contains more object IDs.)
8. Connect the `ZMask` node to the `Mask` input of the `Merge` node and the output of the `Merge` node to the Viewer.

See this screenshot to make the node tree clearer:
![natrontest_nodetree](https://user-images.githubusercontent.com/13981545/29415175-6e3be902-8362-11e7-9fe5-bac4475d9551.png)

So far, everything's working as expected. But now...

9. Add a `Color Correction` node after the `Merge` node.

The problem/bug should become apparent immediately: The Viewer no longer shows the correct composite image, but only the separated light from the `light` sequence. Remove the `Color Correction` node again and everything's back to normal. See the following screenshots...

Correct output without `Color Correction` node:
![natrontest_correctoutput](https://user-images.githubusercontent.com/13981545/29415372-2226bee2-8363-11e7-9ba6-c2723e45823b.png)

Wrong output with `Color Correction` node:
![natrontest_wrongoutput](https://user-images.githubusercontent.com/13981545/29415382-2ce68812-8363-11e7-8c31-f277ffd1351d.png)

This had me stumped for awhile and while trying different things I found that I could sometimes (not always) resolve this by setting the `Output Layer` of the `Color Correction` node to `Composite.Combined.RGBA`. Also, in some cases it helped to first link the viewer to the `Read` node of the `light` sequence and then back to the `Color Correction` node.

What's more, the problem goes away, when connecting the `main` sequence directly to the `Merge` node, without first doing any compositing (diffuse and glossy layers). So, it seems to me that this has something to do with input and output layers... using `Color.RGB(A)` vs. `Composite.Combined.RGB(A)`. But this is where I gave up.

Is this a bug? Or is it intended behaviour? If so, what am I misunderstanding?

Any help would be much appreciated.

### Versions

* **Natron version:** 2.3.2
* **OS version:** Linux Mint 18 64-bit

**Comment by devernay** [comment]
Thanks for submmitting this issue. This is a very cool use case.

Short answer:
- always use the checkerboard button above the viewer to debug your comps

Long answer:
The issue comes from alpha channel handling:
- all your sequences from natrontest_main###.exr are RGB - no alpha
- the merge node thus considers that their alpha is 0
- the Merge4(over) does A+B(1-a), which is the same as A+B since a=0.
- on the other hand, the Light.Combined.RGBA image has an alpha of 1, and it is merged correctly by Merge1 on the transparent background. The resulting image has an alpha of 0 except on the upper-right ball which has an alpha of 1
- color correct sees that its input is premultiplied, so it unpremultiplies it (eg divides by alpha) before processing, then re-premults it, resulting in areas where alpha is 0 being set to black and transparent.

The cure: fix your alphas.
The inputs to Merge4 should have a proper alpha.
I see that the borders are antialiased in Main.DiffCol.RGB, so this image is very probably premultiplied (there is no reason for colors being darker at the objects frontiers), and misses its alpha channel. Same for Main.GlossCol.RGB. Since these alphas were lost, the comp will be wrong in the end (even if it looks like it's good).
Once the inputs to Merge4 have proper alphas, Merge4 will do the proper job, and its output will have alpha=1 at proper places (use the checkerboard, Luke).

At this point, it may look like you have fixed the comp, but the story is not over, and there are other subtle bugs in the comp that should be fixed (unless you're happy with the result).

Actually, the same problem happens with the light sequence: the ball border seem antialiased in Light.Combined.RGBA, but the alpha is 1 everywhere. And your ID mask is not enough to do a proper comp: there seems to be pixels on the border of the ball which are darker but are inside your ID mask. Should they really have an alpha of 1? Probably not. The result is that you will merge dark pixels.

I think that the only way to properly comp this is to get a proper alpha for each object you want to merge over the others. Don't use ID masks - they are OK to apply an effect on an object such as changing its color, but not to extract objects from an image. I don't know how to do it in blender, but this is the only way.

It would be very kind of you if you could fix these issues by getting the proper alpha masks out of blender instead of ID masks, and if we could make a joint Blender/Natron tutorial out of this.

**Comment by marcchristopher** [comment]
Thank you very much for the prompt and detailed reply. I'll be happy to help create a Blender/Natron tutorial, if this use case happens to be interesting enough. :)

And you are, of course, correct: What I thought was a bug, is obviously an alpha/premultiplication issue. I think, from now on I'll make a habit of hitting the `A` key over the viewer more often (and of using the checkerboard button :)).

So, looking for a simple solution, I noticed that deactivating the `(Un)premult` checkbox in the `Color Correction` node does indeed yield the correct output. Needless to say that this is just a quick fix. A better strategy would be to fix the alphas.

As I see it, in this example this will basically consist of correcting the alpha for the `light` sequence. The `main` sequence, on the other hand, should be correct as it is (please correct me, if I'm wrong): The `Merge` operations for re-compositing the render layers basically combine the separate render passes (direct light, indirect light and color) for the diffuse, glossy, transmission and SSS layers... and these don't have an alpha channel. In any case, an alpha channel would be unnecessary here anyway, as the re-combined `main` sequence doesn't need to be put "over" anything.

So, I will try to replace the ID pass in the light sequence with a proper alpha and see, if this yields a more elegant solution. (As a nice side-effect, this would also make it unnecessary to pipe a ZMask into the Merge operation.)

**Comment by devernay** [comment]
BTW, you can directly select the planes to merge in the merge node, so another version of the graph would have only one reader per sequence. You can use Dot nodes if you want to better vizualize the A and B inputs

**Comment by devernay** [comment]
As I mentionned, the passes rendered by Blender seem to be premultiplied. It is especially visible in the COL images: the colors should be solid, but they are darker on the object edges. Blender should also give you an alpha with these. The other passes are probably also premultiplied, but it is less visible. It would be nice if you could get those alphas out of blender. It would also be nice if you could get a proper matte instead of the id mask.
Merge4 should probably not be an "over", but rather a plus (which it is if both inputs have a zero alpha channel)

**Comment by marcchristopher** [comment]
Thanks for following up on this. I have already got correct alphas for the `light` sequence out of Blender: happened to be just a matter of clicking a single checkboy that I had forgotten before. And I'm now using these alphas instead of the ObjectID pass, which seems to work fine. I will collect the new files for a tutorial soon. (By the way: Would you like me to record one or two screencasts? Or would you rather write something yourself so that you can adhere to a certain tutorial format?)

However, I don't think I will be able to get an alpha for the `main` sequence. The alpha channel is correct (i.e. 1 everywhere) in the `Main.Combined.RGBA` layer of the EXR files, but the separate passes (for diffuse light, indirect light and color) do not have an alpha channel (by their very definition). So, in effect, these passes only appear in the RGB flavor in the EXR files, which means that `Merge` nodes are treating the alpha as 0 (see the documentation of the [Merge node](http://natron.readthedocs.io/en/master/plugins/net.sf.openfx.MergePlugin.html). They are, however, premultiplied, as you noted correctly, which is due to the file format (EXR).

One solution would be, of course, to simply use the `Main.Combined.RGBA` layer for the `B` input of the `Merge1` node instead of re-combining the separate passes. In this simple example, this works well, but it also makes it impossible to work on the passes (e.g. denoise them) separately.

Another solution would be to make the `Merge4` node (the composite of the render passes) somehow output RGB instead of RGBA and check the `A` checkbox in the subsequent `Merge1`. `Merge1` will then treat that alpha as 1 and the composition works without problems. But how to make a `Merge` node output RGB?

As to setting `Merge4` to Plus instead of Over... Hmm, not sure about that. If I understand correctly, the Plus (Add) operator ignores the Alpha of the `A` input (so that an opaque red added to an opaque green become yellow), whereas the usual Over operator respects the Alpha. Please correct me, if I'm wrong...

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#218
