### ISSUE TITLE
Recalling window/panel configuration with project?

### ISSUE THREAD

**Issue by unfa** [MrKepzie/Natron#1670]
Every time I restart Natron (and due to hung rendering processes - sometimes it's very often) I have to detach my viewer panel to a separate window, drag it to my second screen and resize to my liking.

Could Natron store the windows and panel configuration within the Project file and recall these settings on loading?

Or maybe I'm just missing some options to flick?

**Comment by MrKepzie** [comment]
There’s an option for that in the Preferences, under User Interface: “Load workspace embedded within projects”. It’s unchecked by default

**Comment by unfa** [comment]
Thank you! I searched the settings but I overlooked that!

**Comment by MrKepzie** [comment]
There’s an option for that in the Preferences, under User Interface: “Load workspace embedded within projects”. It’s unchecked by default
On 12 Sep 2017, at 15:49, unfa <notifications@github.com<mailto:notifications@github.com>> wrote:


Every time I restart Natron (and due to hung rendering processes - sometimes it's very often) I have to detach my viewer panel to a separate window, drag it to my second screen and resize to my liking.

Could Natron store the windows and panel configuration within the Project file and recall these settings on loading?

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#224
