### ISSUE TITLE
Question, natron 3.0 needs new build instructions

### ISSUE THREAD

**Issue by bn0785ac** [MrKepzie/Natron#1693]
i use this buildscript
https://aur.archlinux.org/packages/natron-git

BUT i cant run natron   (i've got some segfaults)

https://aur.archlinux.org/packages/natron-git

i use archlinux-64 *piledriver CPU*, and its updated

**Comment by devernay** [comment]
Hi,
The build instructions are in the source repository (INSTALL_LINUX.md).
Sorry, but you must ask the arch linux package maintainer to update the PKGBUILD.
Note that Natron 3 is not yet ready, use Natron 2.3 for real work.
CLosing this.

**Comment by bn0785ac** [comment]
sorry


but i'm the mantainer of this pkgbuild  (i'm trying to build "stable" natron snapshots)



but i'm freezed, because the most recent commits are related to  natron3, instead iof 2.3



with my pkgbuild   BUILDS (just like a travis bot).... BUT i cant run the package

**Comment by devernay** [comment]
You should build the RB-2.3 branch.
I cannot help you much with your build, unfortunately. 
Le 8 nov. 2017 11:09 PM, bn0785ac <notifications@github.com> a écrit :sorry
but i'm the mantainer of this pkgbuild  (i'm trying to build "stable" natron snapshots)
but i'm freezed, because the most recent commits are related to  natron3, instead iof 2.3
with my pkgbuild   BUILDS (just like a travis bot).... BUT i cant run the package
