### ISSUE TITLE
It is recommended to modify the color selector

### ISSUE THREAD

**Issue by githob605608886** [MrKepzie/Natron#1713]
The current natron color selector is not very friendly to use
The open source software, opentoonz, has a very good color selector. It should be a reference.

The OFX plug-in option should be the color selector, but the natron is displayed as a numeric box

**Comment by nicholascarroll** [comment]
Hello @githob605608886 , do you mean this #1592 ? 
The problem comes from the Qt GUI kit. Unfortunately a small number of Qt's widgets are really bad and Qt never fixes them. So we find the same thing in the [latest version of Qt, 5.10](http://doc.qt.io/qt-5/qcolordialog.html)
If this is your issue, you can close this one and put your vote on #1592, I logged that issue and I would like to have other users help bump the priority which is currently set to Low.
