### ISSUE TITLE
Natron crashes after ~100 frames of playback on ubuntu.

### ISSUE THREAD

**Issue by detomastah** [MrKepzie/Natron#1717]
I downloaded Natron 2 from official site. Installed in on Ubuntu 16.04.
It seem to work... except that after ~100 frames of playback it exits **without any crash report**!
I tried to debug with `gdb` but it report normal exit.

```
(gdb) run
Starting program: /data/Natron2/bin/Natron 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffecd5b700 (LWP 3103)]
Natron Version 2.3.4
Copyright (C) 2013-2017 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
Fontconfig error: Cannot load default config file
Failed to connect local socket to IPC_COM
Info: init.py script not loaded (this is not an error)
Info: initGui.py script not loaded (this is not an error)
[Thread 0x7fffecd5b700 (LWP 3103) exited]
[Inferior 1 (process 3098) exited normally]
(gdb) 
```

### Steps to Reproduce

1. Open Natron
2. Add any Input (Read, Colorwheel etc)
3. Press play and wait 2-3 seconds.
4. See it exit

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions
Natron Version 2.3.4
Ubuntu 16.04

**Comment by detomastah** [comment]
OK, figured that out - probably too little disk space in default cache folder. Some message would be appreciated or even crash report. If you point me which file I should modify, I'll add it.

**Comment by devernay** [comment]
There's still something wrong here, since it shouldn't die that way. Can you put a breakpoint in "exit" to check what's the exit path?
BTW, Natron is a script, so it's probably not the executable you should execute. The script executes the crash handler (which is a small binary), which executes the real Natron. I don't remember the names, but both binaries are Natron-something.
Disk space checking is really an issue. Imagine you are rendering frames on the same disk as your cache. We have to check every time we create a cache file. It is probably not done ATM.
Where this happens is
https://github.com/MrKepzie/Natron/blob/RB-2.3/Engine/Cache.h
https://github.com/MrKepzie/Natron/blob/RB-2.3/Engine/Cache.cpp
https://github.com/MrKepzie/Natron/blob/RB-2.3/Engine/CacheEntry.h

**Comment by detomastah** [comment]
My idea is to do that periodically and inform user upfront. For example you check every 30 seconds and inform user that disk space is low. It can be even done after startup. I'll do what you advised and check.

**Comment by devernay** [comment]
any feedback?

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#235
