### ISSUE TITLE
Natron doesn't use OpenGL rendering with ALL plugins installed and is working really slow. All requirements are fully met. 

### ISSUE THREAD

**Issue by Piowiole** [MrKepzie/Natron#1718]
I was trying to add Slit Scan effect and noticed that rendering is running very slow. 

I opened "Preferences > Plug-ins" where saw that all plugins have OpenGL checkboxes disabled and i can't make it run. 

I don't know what else i should write here, i'm not a programmer. Please help me solve this problem. 

ABOUT WINDOW

Natron version 2.3.4 Release.
Python 2.7.14
Qt 4.8.7 / 4.8.7
Boost 1_65_1
Cairo 1.14.10 / 1.14.10
Hoedown 3.0.7 / 3.0.7
Ceres 1.12.0
OpenMVG 0.9.0
OpenGL renderers:
GeForce GTX 1060 with Max-Q Design/PCIe/SSE2 from NVIDIA Corporation
OpenGL version 4.5.0 NVIDIA 375.82 with GLSL version 4.50 NVIDIA

OS Debian Stretch

**Comment by devernay** [comment]
Well, SlitScan *is* very slow, because it needs many images to compute its result.
Most plugins aren't OpenGL-capable (except ShaderToy and the HitFilm plugins if you installed them).
If you are using a compressed video as source, then converting it to individual frames, and using an image reader instead of a video reader, may help. Google is your friend: "ffmpeg extract frame"

**Comment by devernay** [comment]
closing this issue, as nothing is wrong here
