### ISSUE TITLE
Switch node always uses format/ROI of input0

### ISSUE THREAD

**Issue by CameraRick** [MrKepzie/Natron#1747]
### Problem

The Switch always uses the complete format of the input 0 it seems. So if two sources of different formats are connected, it will only output the one of input0, regardless if it's larger or smaller.

Watch here: https://youtu.be/rDV9Aiu5KCE

**Expected behavior:**
The Switch should switch the complete input including formats etc, regardless of others

**Actual behavior:**
The Switch uses the format only of input0

### Steps to Reproduce

1. Create/import two sources with different formats (e.g. two Constants, one 4K and one HD
2. Create a Switch node and connect both inputs
3. Switch the inputs and see the ROI/format not switching

### Versions

* **Natron version/commit** 2.3.9 as well as 2.3.10 (snapshot 31032018)
* **OS version:** Windows 10 Professional

**Comment by devernay** [comment]
Format cannot change over time, so it takes the format from the first connected input, but the rod should be taken from the selected input. Will check your video to see if something is not normal. Le 1 avr. 2018 00:22, lucas pfaff <notifications@github.com> a écrit :Problem
The Switch always uses the complete format of the input 0 it seems. So if two sources of different formats are connected, it will only output the one of input0, regardless if it's larger or smaller.
Watch here: https://youtu.be/rDV9Aiu5KCE
Expected behavior:
The Switch should switch the complete input including formats etc, regardless of others
Actual behavior:
The Switch uses the format only of input0
Steps to Reproduce
Create/import two sources with different formats (e.g. two Constants, one 4K and one HDCreate a Switch node and connect both inputsSwitch the inputs and see the ROI/format not switching
Versions
Natron version/commit 2.3.9 as well as 2.3.10 (snapshot 31032018)OS version: Windows 10 Professional

**Comment by devernay** [comment]
Confirmed 100% normal.
What I *could* do is set the format from the switch parameter *only* if it is not animated...

**Comment by devernay** [comment]
should be fixed in next snapshot, reopen if not

**Comment by CameraRick** [comment]
That's totally fine like this. I agree, when animating a switch it's a desaster, but for controlling setups the Switch is the only node able to do this.

However, in my case, the Switch IS animated (or Expression linked to a pulldown at least), so this won't work anyway I guess?

**Comment by devernay** [comment]
As long as it doesn't have a keyframe, it's not considered to be animated, so expressions are ok.
If your expression uses animated parameters, I don't guarantee anything.

**Comment by CameraRick** [comment]
It's only expression linked to a pulldown choice, I don't even know if you can animate those. It makes also no sense for any user to animate this, as the purpose of that switch is to give you a setup screen that you can't really utilize else.

If so we're good with Python I'd make a button that creates ankeying setup from the selected choices. But well, I'm not anything with Python :(

**Comment by CameraRick** [comment]
I wanted to try it again but somehow the script is completely broken with Reformats now. Actually in all new scripts, too.
Issue is with "to Box" type: https://i.imgur.com/xMyglqc.png
Doesn't matter what I fill, doesn't matter if forced shape or not, it doesn't reformat to the Box. It always seems to use the format set in "to Format". Even if I go to scale and set it to e.g. 0.5, and switch "to Box" then, it flips back to the values of "to Format"

BUT when we leave that out, the format-switch with the Expression link works. Thanks :)

**Comment by devernay** [comment]
please test with next snapshot (should be there within 2h). If it's OK, I'll release 2.3.10 tonight.

**Comment by CameraRick** [comment]
Sorry for my late reply, I was at work and couldnt check.
I now tested with the 2.3.10 final, and it works as it should. Thank you :)
