### ISSUE TITLE
Plans For 3D Support

### ISSUE THREAD

**Issue by saphtea** [MrKepzie/Natron#1777]
Has there been any work done on 3D support in Natron? If so, where in the source has that work been started just to make it easier for contributors?

Then of course if not, what do the plans look like so we can help bring aboard potential contributors? Thank you for your time, I appreciate it!

**Comment by devernay** [comment]
The work on 3D has no started in the code.
3D support probably means metadata support in the graph, so that other data than just images flows through the graph. The work on metadata hasn't started either. Take a look at the Nuke doc on metadata to see one possible solution.
When development stalled, we were reworking the engine and the caching system completely, because it is still buggy in Natron 2.3, but even this task was not completed.
As for onboarding contributors, there is a "Contributing" section in the toplevel README.md: https://github.com/NatronGitHub/Natron#contributing
