### ISSUE TITLE
Roto Node: What happened to the invert mask feature

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#224]
I was testing Natron with the chromakey and roto again.  I drew a roto to mask out the body of the talent from the rest of key.  I went to invert the rectangle mask roto and there was no ability to do so. 

![whereistheinvert](https://cloud.githubusercontent.com/assets/7956901/4340568/65d65aa0-402f-11e4-9fb4-975e6aadafbb.png)

Now in Natron v0.9.6 (image below) the Roto node had the invert feature right beside the activate operator.  Was there some kind of invert mask issue with new changes in Natron?

![natronv0 9 6](https://cloud.githubusercontent.com/assets/7956901/4340582/92d68246-402f-11e4-865f-117ced0d046d.png)

**Comment by devernay** [comment]
All our nodes that use a mask provide an "invert mask" checkbox.
I will add an "expand to project size" checkbox to the invert node to invert masks for plugins that don't have that checkbox.

**Comment by devernay** [comment]
rather than the "expand to project size" checkbox, I will do an "InvertAlpha" node that lets the user chose the minimum size of the output (project size, format size, custom size, as in generators)

**Comment by blackearth2014** [comment]
Fred, I like the invertAlpha node idea.

**Comment by PostPollux** [comment]
Ok, I'm not really in the code, so it's hard for me to judge if something is easy and effective, or not.

But wouldn't it be easier to change the code of the roto node? So that the alpha of the roto is by default black for the whole format. The format would be the project settings, as long as there is no bg input connected.
Now if you put an invert node after the roto it should work without the need of an extra InvertAlpha node. I think it would also get rid of this bug https://github.com/MrKepzie/Natron/issues/1256

Well I guess the downside is a performance loss, as you will pass on a full alpha channel and not just a cropped version of it. Would that be a significant performance loss?

**Comment by devernay** [comment]
OK I'm closing this.

The *only* clean solution is to put a Crop node to extend the Roto to the desired format, and then an Invert node to invert alpha. That way, the user knows *exactly* that the extent of the mask is limited to the Crop size.

This is particularly important in the case where there is a Transform node after the Roto. in this case, the transform should *of course* be placed between the Roto and the Crop, and not after the Crop or after the Invert.

This adds two nodes to the graph, but makes the processing self-explanatory.
