### ISSUE TITLE
TransformNode ScaleDown issue

### ISSUE THREAD

**Issue by mifth** [MrKepzie/Natron#258]
Hi again.

I found some issues with TransformNode. 

- ScaleDown looks very sharpen and some artifacts appear for small scale sizes.
- Rotation makes no antialiasing for image's edges. It's especially seen if we scaleDown and rotato to30 degrees.

Nuke: http://i.imgur.com/X6Ef9aX.png
Natron: http://i.imgur.com/u8NIKUK.png
Project: https://dl.dropboxusercontent.com/u/26887202/Natron/test_transforme2.zip

**Comment by mifth** [comment]
@MrKepzie @devernay Hi.
Sorry for bothering. I just would like to ask when mipmaps will be implemented? In what Natron version we could expect them?
This is one of important things which Natron misses. ScaleDown feature.

Thanks.

**Comment by MrKepzie** [comment]
Hi We Did not havé a chance to do it yet, I have no eta on this though

**Comment by mifth** [comment]
Ahh.. It's too bad. I still cannot use Natron for production as i need to ScaleDown a lot images/effects. But i'll wait for sure!

Anyway you do great job!

**Comment by devernay** [comment]
almost done

**Comment by mifth** [comment]
@devernay great news! Waiting to test it!

**Comment by devernay** [comment]
still have to fix image borders

**Comment by mifth** [comment]
@devernay Hello!

I tested latest snapshot. Downscaling works perfectly! Thank you a lot! Now i can use Natron for my production.

The only isue i found that Downscaling algoright is always the same. I guess it's always Cubic for all algorithms. Also, Impulse works in Natron too. But other algorithms do not work.

Here is a comparison with Natron and Nuke downscale algorithms http://youtu.be/bEwNX1Q747U
The testing file is at the first post.
I will reopen the issue for a while if you don't mind.

**Comment by mifth** [comment]
Ahh... i have no rights to reopen the issue.

**Comment by devernay** [comment]
Unless you point me to a peer-reviewed publication, or an image processing or computer graphics textbook saying that anything else than bilinear should be used for supersampling, this should be considered a Nuke bug and not a Natron bug.
Please report this to The Foundry, not us.
There is absolutely no reason to use bicubic or other sophisticated interpolation functions for supersampling: supersampling is supposed to approximate the integral of the image over the surface of a pixel using many samples. What would motivate using an *interpolation* function to compute an integral over *several* pixels? Nothing, sorry.
I used bilinear, not impulse, to avoid aliasing due to supersampled pixel borders, and it does this job perfectly. Cubic is just overkill. Compile your own Natron with cubic or whatever you want: it's just doing it wrong.


I can show you more Nuke bugs related to supersampling if you want. Do that shape in Nuke, you'll notice horizontal artifacts. Do you still think Nuke should be considered as the gold standard?
```
   /
  / |
 /  |
|   |
|   |
 \  |
  \ |
   \|
```

**Comment by mifth** [comment]
@devernay hi.
It seems you misunderstood a bit.
I meant that Nuke has many interpolation methods, when we change scale method(Linear, Cubic, Lacoz, Sinc etc.)
But Natron has only one interpolation method.
I'm sure that Fusion and AE have many downscale interpolation methods too.

Here is a screenshot of my explonation from Nuke:
![cache0](https://cloud.githubusercontent.com/assets/2251298/6522972/2e9a8a38-c3fc-11e4-96da-b97d62b54f79.png)
