### ISSUE TITLE
Feature Request: Viewer Overlay Controls

### ISSUE THREAD

**Issue by OldSkoolVFX** [MrKepzie/Natron#383]
You currently have a global overlay on/off toggle if you right click in the viewer pane.  However it is all-or-nothing.  This is very inconvienient and messy.  The following are ideas to clean up the overlay situation and make it easier to use and switch between them.

1: A menu activated from the viewer controls with a menu that allows one to toggle on or off the overlays that are available at that particular time (in the node bin).  The advantage would be a single place to look instead of going hunting for the overlays in the bin panels and thus a quick way to toggle them on or off.

I think this is the best option as it's in the viewer that overlays are need and used.  Going back to the node properties bin wastes time and slows the work flow.  Having to only use the active node does not let one work with more than one node.  Minimizing nodes make me have to fiddle with the node bin and slows the process.  That's why I think that the overlay controls need to be with the viewer controls.

Alternate/related ideas:

2:  An option in the related node settings panel to view or not view a specific overlay in the viewer pane.

3: An option on the top of the node properties bin to only show the active node's overlay.

4: An option on the top of the node properties bin to automatically minimize non-active panels for use if you implement that minimization toggles overlays off.  This would be useful on it's own.
- Thanks

**Comment by MrKepzie** [comment]
Can you point me to a use-case where you need to have several overlays to work on at the same time ?
Having another option in the settings panel will make it hard for other people to understand why some overlays of a node are not displayed. We don't want that at some point, it is easier to create a new node to achieve the same result, rather than understand why the older one is not doing what you want. 

3: what is the active node ? The selection ? there can be multiple nodes, and to me it would achieve exactly the same as today : you would need to go to the node graph to select nodes, where-as today you just double-click the nodes to open their panel. 

4: i'll implement that.
