### ISSUE TITLE
Feature Request: Slice Tool

### ISSUE THREAD

**Issue by OldSkoolVFX** [MrKepzie/Natron#384]
A slice tool like Nuke's would be very useful for evaluating images like in keying etc.  The slice tool only shows the pixle values in a histogram of the pixles only in that line as opposed to a histogram of the entire image.

**Comment by devernay** [comment]
I agree this would be useful ( although it's not a histogram, just a curve showing the pixel values along the line)

**Comment by nicholascarroll** [comment]
It would be great if this could be integral to the viewer (not a node). And when you move the mouse along the slice line in the viewer, its position would show as a vertical line on the graph.

**Comment by nicholascarroll** [comment]
I would like to make some more suggestions on how it might work:
1. Options to show the graph lines as one or more of R,G,B,A,Luminance. 
2. When you draw the line, the start point is the left end (x axis origin) in your graph and the end point is the right end of the graph. 
3. Option to click the start of the line in one frame, the end in another frame. So for example if its the same pixel in the start and end, you will get a graph of how that pixel's colour changes over the shot. 
4. Option to show both A side and B side of the viewer as lines in the graph. In an RGB, this would be a bit crowded, but in luminance only or alpha only, it would work well.
5. Ability to use one of the values as the scale for the y axis.

Also some more food for thought: often a person using a slice graph would actually be happier to be sampling a region (ie waveform) rather than individual pixels, especially when there is noise. But convenience and simplicity, and the most common use case, would be the most important thing.

**Comment by nicholascarroll** [comment]
I see this has been deprioritized. However it really is an essential feature that I think many would use alot.

**Comment by devernay** [comment]
I totally agree, it's just that the feature list for 2.1 is closed. Don't worry.

**Comment by nicholascarroll** [comment]
OK I'll try not to worry.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#90
