### ISSUE TITLE
CurveEditor - handle free - enhancement

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#386]
![curve_handle](https://cloud.githubusercontent.com/assets/8054856/5631480/510e3c08-95c7-11e4-9853-cb875a884e69.jpg)

I don't know if is a deficit of my know how of Natron, but on bezier of Curve Editor the handle are locked in length, I have try various kind of interpolation but all length of handle seem locked.
If there isn't a way for have handles free could be nice to have.

**Comment by MrKepzie** [comment]
Handles in the curve editor do not mean the same thing as for the bezier curves! 
Typically in the curve editor, we can’t allow the curve to go backward, as in the Roto you’re free to draw anything.

**Comment by fPaglia** [comment]
Must say it would be a very appreciated addition because as the curves'
handle are now we have to add more keyframe to achieve a different
interpolation and this normally drives more error and require more fine
tuning.


2015-01-06 17:25 GMT+01:00 Alexandre Gauthier <notifications@github.com>:

> Handles in the curve editor do not mean the same thing as for the bezier
> curves!
> Typically in the curve editor, we can’t allow the curve to go backward, as
> in the Roto you’re free to draw anything.
>
> > On 6 Jan 2015, at 17:22, Alessandro Dalla Fontana <
> notifications@github.com> wrote:
> >
> > <
> https://cloud.githubusercontent.com/assets/8054856/5631480/510e3c08-95c7-11e4-9853-cb875a884e69.jpg>
>
> > I don't know if is a deficit of my know how of Natron, but on bezier of
> Curve Editor the handle are locked in length, I have try various kind of
> interpolation but all length of handle seem locked.
> > If there isn't a way for have handles free could be nice to have.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/MrKepzie/Natron/issues/386>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/386#issuecomment-68888616>.
>



-- 
Francesco Paglia
Vfx and Production Supervisor

mobile  +39 347.82.12.473
e-mail   f.paglia.80@gmail.com

**Comment by adallafontana** [comment]
"Handles in the curve editor do not mean the same thing as for the bezier curves!"
yes! I know, was only an example for a drawn curve.
![boing](https://cloud.githubusercontent.com/assets/8054856/5634093/4cbe3a0c-95dd-11e4-9bf1-02c6bde83949.jpg)
Like said Francesco is important stuff for animator and is a must-to-have in every animation software.
Less keyframes = simplest control.
Also when Natron will have dope sheet or similar.
On the screenshot a stupid example: for drawing a "boing" curve:
if you have control over the handle length you need half keyframes or anyway you have more control.

**Comment by MrKepzie** [comment]
This is not as simple as it looks, because increasing the length of the tangent, would mean move the left/right bezier point by some extent, and at some point it can make the curve go
backward. The technicality is to block the user when it cannot be extended further more

**Comment by nitsch** [comment]
@MrKepzie, Blender seems to have solved this nicely in its curve editor. It does not really block the movement at some point but just sort of saturates the control point's influence beyond that point. You may want to try it yourself just to get a feel for it. I think a similar behaviour would fit Natron as well.

**Comment by MrKepzie** [comment]
Since our interpolation methods are heavily based on the principle that Hermite and Bezier representation are interchangeable with tangents at 1/3 of the P0/P3 points of the bezier control polygon, we're very unlikely to implement it any time soon. That would require a major re-write of all the internals of our interpolators and would probably slow-down the whole system a lot.
