### ISSUE TITLE
Transform node concatenate motion blur issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#394]
![motion_blur](https://cloud.githubusercontent.com/assets/8054856/5692096/d5fdc042-98e6-11e4-97e3-494f88e708d6.jpg)

I don't know if this is possible in other software, but if I have more that one animated transform node (or corner pin) only the motion blur of last in chain is calculated.

**Comment by MrKepzie** [comment]
Filtering and motion blur only applies on the last Transform, for all other nodes concatenated it is ignored.

**Comment by adallafontana** [comment]
Ok, I will change my tree of node, but will be in absolute so?

**Comment by MrKepzie** [comment]
I don't understand the question, sorry

**Comment by adallafontana** [comment]
I mean that is not possible have this improve in the future, is so and that's it, is a problem of core, rendering, etc.... or something similar, just to know.

If is it so you can close this issue, I understand.

**Comment by MrKepzie** [comment]
The very fact of activating Transform concatenations means that the filtering (hence motion blur) is applied only once to yield the best output quality. 
You can disable transform concatenations in the Preferences—> General if you want, but then the output quality will be worse because it will be filtered multiple times.

**Comment by adallafontana** [comment]
Ok thanks for the explained.
Anyway I'm astonished for the really good quality of motion blur and in general for every pixel filter.

alessandro
