### ISSUE TITLE
libraw-based reader (for raw image support - CRW/CR2, NEF, RAF, DNG, and others)

### ISSUE THREAD

**Issue by Barbone** [MrKepzie/Natron#408]
I would like to be able to import CR2 sequences right into app as I do in AE. Nuke uses DCRAW.

**Comment by blackearth2014** [comment]
What camera generates this file type?

**Comment by sbtread** [comment]
http://filext.com/file-extension/CR2

**Comment by Barbone** [comment]
Canon cameras.

**Comment by blackearth2014** [comment]
thanks

**Comment by devernay** [comment]
Did you try TuttleOFX? (TuttleRawReader)
We may add a reader plugin based based on libraw to the default set of readers.
http://www.libraw.org/

**Comment by Tungee** [comment]
Would this also mean DNG Support!?!?

2015-01-19 23:44 GMT+01:00 Frédéric Devernay <notifications@github.com>:

**Comment by MrKepzie** [comment]
Basically yes

**Comment by fabiencastan** [comment]
> We may add a reader plugin based based on libraw to the default set of readers.

I still don't understand why you loose time to rewrite things that are already done in TuttleOFX instead of bringing new stuff to the community. The goal of openfx is to write a plugin once and to use it in multiple applications. There is no interest to rewrite the same plugin in the same format with the same library behind...
If you need some specific improvements, please contribute or report it.

From the OpenFX documentation:
"It allows plug-ins written to the standard to work on any application that supports the standard. This avoids the current per application fragmentation of plug-in development and support, which causes much heartache to everyone, plug-in developers, application developers and end users alike."

**Comment by devernay** [comment]
Hi Fabien,

We encourage users to try out and use TuttleOFX whenever something is missing from Natron.

But we have several issues with TuttleOFX, which can not be solved unless something is changed on your side.

There are two kinds of issues: functional issues (the plugin is unstable, or is not easy to use in a compositing environment) and deployment issues (the plugin is difficult to compile and distribute).

Let us take readers for example:
- all our readers have colorspace choices (based on OCIO)
- all our readers support renderscale (images can be downscaled for faster preview) and proxy mode
Users wanted these features, now they have them, and they would not want any of the features we put in every OpenFX plugin to be removed. We get a lot of feedback from users, and most issues or feature requests are solved within a few hours.

Because of the design choices that were made in TuttleOFX (many dependencies, including boost, use of GIL, etc.), it doesn't seem to be a good idea to backport our plugins and readers to TuttleOFX, although we contributed to TuttleOFX (*) and will still contribute. I already signaled issues about dependencies in TuttleOFX, but they are almost unsolvable. Plugins have to be small, self-contained, and should have as little dependencies as possible, in order to fulfil the role you quote from the OpenFX documentation.

We are *exactly* following these recommendations:

We try very hard to make our plugins portable, fast, well-maintained, and easy to use for compositing. They run in Natron, in Nuke, in TuttleOFX's sam, in DaVinci Resolve, and probably in many other OpenFX hosts (although we never got reports from Fusion, Scratch, or Shake users).

[openfx-misc](https://github.com/devernay/openfx-misc) is a set of more than 60 plugins, with absolutely *no* dependency. We are pretty sure they are more portable than anything else you could find, and that was how OpenFX was designed to be used. Even DaVinci Resolve (Lite) users are happy with these. We do not want to use [GIL](http://www.boost.org/doc/libs/release/libs/gil/) for image processing, because it makes code hard to develop, hard to maintain, and the produced code may run slower than well-coded array-based C image processing. We use the [standard OpenFX libraries](https://github.com/devernay/openfx), initially developped by @BrunoNicoletti, and think they are a very good piece of software.
We extended them with [lightweight C++ classes](https://github.com/devernay/openfx-supportext), the same way it was done in the original libraries. We also support many [OpenFX extensions which are being debated at http://openeffects.org](http://openeffects.org/standard_changes) , such as [Deep Images](http://openeffects.org/standard_changes/deep-images-multi-plane), [Multiview](http://openeffects.org/standard_changes/224), and Transform concatenation. We didn't want to rewrite the OpenFX libraries, because we want plugin developers to be able to easily migrate from the official version to our fork. We are developing these changes under the same license as the original library, so that whenever they (OpenFX) ask us to contribute back our changes, it can be done in a few seconds, and we will be very happy to do so.

[openfx-io](https://github.com/MrKepzie/openfx-io/) is a collection of readers, writers, and colorspace conversion tools. Although it uses as few dependencies as possible, it already has some issues with it (e.g. if a plugin uses a library which is already used by the host, such as OCIO). These issues can not be solved, unless we link with static libraries (which we may do one day).

@MrKepzie wrote a small guide ([part 1: basics](https://github.com/MrKepzie/Natron/wiki/OpenFX-plugin-programming-guide-%28Basic-introduction%29), [part 2: the Invert plugin](https://github.com/MrKepzie/Natron/wiki/OpenFX-plugin-programming-guide-%28Invert-plugin-walkthrough%29)) on how to develop OpenFX plugins using the C++ library, and @BrunoNicoletti [wrote another one](https://github.com/ofxa/openfx/tree/master/Guide), which doesn't even use a Support library. This is how plugins should be: lightweight and efficient.

In TuttleOFX, every plugin is a separate binary, so that if we link statically each plugin with all dependencies (including many boost libraries), the resulting distribution is several Gb (gigabytes, yes). We already asked if you planned to put all the plugins in a single binary to solve this issue (as it is done in most commercial plugins sets, such as those by GenArts).

Some of the TuttleOFX plugins don't work well when used in another OpenFX host than TuttleOFX's sam, for example TuttleAVReader and TuttleAVWriter. They are probably perfect when used for transcoding with sam, and fulfil your needs, but they don't fit very well in a compositing environment.

For all these reasons, we had to start a new set of basic plugins. Now that Natron has python scripting, users start making great things which these basic bricks: exactly what OpenFX was made for.

Finally, please note that we accept issues from users who use another OpenFX host than Natron and try to solve these too. We're not Natron-centric at all in developing our plugins. We also accept external contributions, and you are welcome to contribute.

(*) see https://github.com/tuttleofx/TuttleOFX/issues/353 https://github.com/tuttleofx/TuttleOFX/pull/364 https://github.com/tuttleofx/TuttleOFX/pull/358 https://github.com/tuttleofx/TuttleOFX/pull/236 https://github.com/tuttleofx/TuttleOFX/pull/235 https://github.com/tuttleofx/TuttleOFX/pull/234 https://github.com/tuttleofx/TuttleOFX/pull/233 https://github.com/tuttleofx/TuttleOFX/pull/232 https://github.com/tuttleofx/TuttleOFX/pull/225 https://github.com/tuttleofx/TuttleOFX/pull/226

**Comment by fabiencastan** [comment]
> functional issues (the plugin is unstable, or is not easy to use in a compositing environment)

I was not aware that you still have troubles.
You said, in a compositing environment, but it works fine for us in sam and Nuke.
Have you seen that in other softwares than Natron?

> deployment issues (the plugin is difficult to compile and distribute).

Why?

> Let us take readers for example:
> all our readers have colorspace choices (based on OCIO)
> all our readers support renderscale (images can be downscaled for faster preview) and proxy mode Users wanted these features, now they have them, and they would not want any of the features we put in every OpenFX plugin to be removed. We get a lot of feedback from users, and most issues or feature requests are solved within a few hours.

You never tried to discuss with us about that.

> Because of the design choices that were made in TuttleOFX (many dependencies, including boost, use of GIL, etc.), it doesn't seem to be a good idea to backport our plugins and readers to TuttleOFX, although we contributed to TuttleOFX (*) and will still contribute. I already signaled issues about dependencies in TuttleOFX, but they are almost unsolvable. Plugins have to be small, self-contained, and should have as little dependencies as possible, in order to fulfil the role you quote from the OpenFX documentation.

We only have a dependency to some boost libraries.
Image processing plugins (like openfx-misc) have no dependencies at all. Most of them use GIL internally but its header only and has no impact.

> In TuttleOFX, every plugin is a separate binary, so that if we link statically each plugin with all dependencies (including many boost libraries), the resulting distribution is several Gb (gigabytes, yes). We already asked if you planned to put all the plugins in a single binary to solve this issue (as it is done in most commercial plugins sets, such as those by GenArts).

The build with all dependencies included is 135Mo. There is no reason to statically link each plugin. We use rpath with to versionned libs.

> Some of the TuttleOFX plugins don't work well when used in another OpenFX host than TuttleOFX's sam, for example TuttleAVReader and TuttleAVWriter. They are probably perfect when used for transcoding with sam, and fulfil your needs, but they don't fit very well in a compositing environment.

It works fine in Nuke.

> For all these reasons, we had to start a new set of basic plugins.

Yes, it takes time to discuss with the community. But it's important to create a sustainable environment for the project. IMHO, OpenFX is a really good way to federate developments in the open source community.
So yes, it makes me crazy to see people creating exactly the same plugin instead of taking time to federate works. TuttleOFX is specialized on IOs and I do not understand that you are not trying to work with us.

> Finally, please note that **we accept** issues from users who use another OpenFX host than Natron and try to solve these too.

There would be no interest to use OpenFX without that.

**Comment by MrKepzie** [comment]
ReadOIIO is able to read the following formats via LibRaw: 

       "bay", "bmq", "cr2", "crw", "cs1", "dc2", "dcr", "dng",
        "erf", "fff", "hdr", "k25", "kdc", "mdc", "mos", "mrw",
        "nef", "orf", "pef", "pxn", "raf", "raw", "rdc", "sr2",
        "srf", "x3f", "arw", "3fr", "cine", "ia", "kc2", "mef",
        "nrw", "qtk", "rw2", "sti", "rwl", "srw", "drf", "dsc",
        "ptx", "cap", "iiq", "rwz"
The windows & mac versions of Natron already have support for it. I just updated the linux build server so it also includes support for these file formats, it will be available in ~30minutes via snapshots. There should be no need to develop a separate LibRaw-based only Reader.
