### ISSUE TITLE
Color Picker: Ctrl+Alt+click should sample color from the input of the viewed node

### ISSUE THREAD

**Issue by Montaire** [MrKepzie/Natron#454]
In nuke there is a hotkey to sample the source image instead of the visible one.
It would be nice to have one here too.

**Comment by MrKepzie** [comment]
Care to elaborate with maybe a screenshot ? Are you talking about the color picker ?

**Comment by blackearth2014** [comment]
One operation for example of what Montaire is talking about is when using the Grade node. When you are mapping the black and white points, you have to disable the node once you mapped the black point. The white points gets slightly shifted and can remap the white point to a different hue. This is especially necessary when generating contrast or expanding saturation of a image that looks like was was captured in log space or the codec compressed the color range. Canon and Panasonic has a feature called cine style in their cameras that compresses the shadows and highlights into the midrange because of the details the AVCHD throws away. It's not perfect but it makes a difference of small cameras.

**Comment by Montaire** [comment]
![natron](https://cloud.githubusercontent.com/assets/9551575/6128016/99b9a5b6-b131-11e4-9f2c-269e079dc351.png)
Here I sampled the picture with Ctrl Alt Shift. So the average in the box is not green, but purple.

**Comment by MrKepzie** [comment]
What if there are multiple readers upstream ?

**Comment by Montaire** [comment]
Really good question.
It seems nuke simply does nothing.

**Comment by devernay** [comment]
keystroke should be Ctrl+Alt+click (Ctrl+Alt+shift+click for a rectangle)
marked https://github.com/MrKepzie/Natron/issues/1371 as duplicate

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#96
