### ISSUE TITLE
Viewer scale handles doesn't work + svg files enhancement

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#465]
Hi
Linux x64 - 1.2 version

1. Viewer scale handles doesn't work, other handles work.

2. Are there any plans to improve ReadNode to support SVG files ?

Regards

**Comment by MrKepzie** [comment]
Hi, the scale handle bug was already fixed. We will apply a minor patch to Natron 1.2 soon.

SVG support is already a feature that was requested, especially via the Roto node. That is definitely something doable since Cairo (the library used for vector graphics) does support SVG. It's just a matter of doing it.

**Comment by manuelsongokuh** [comment]
hello
sorry i'm back here for ask you:
there is supported full SVG (inkscape)? or not added feature natron yet? (2.0)?

**Comment by olear** [comment]
SVG is not supported, someone has to make the plugin.

**Comment by MrKepzie** [comment]
SVG is supported via Cairo, it should be handled in the roto node, but it would require major work mainly for the user interaction

**Comment by devernay** [comment]
Cairo cannot load SVG files, you need something like librsvg for that.
A reader using librsvg for reading and cairo for rendering should be written (ReadSVG) with options to scale and offset the SVG file.

**Comment by olear** [comment]
Added ReadSVG in openfx-arena trunk, may need some adjustments but seems to work ok. DPI param controls the size
![screenshot-15](https://cloud.githubusercontent.com/assets/7461595/8277295/8f219b34-18c1-11e5-8bae-957902b1cbe3.png)
