### ISSUE TITLE
DirBlur doesn't use CPU multi-processes issue

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#525]
![dir_blur](https://cloud.githubusercontent.com/assets/8054856/6431224/09dd315e-c029-11e4-9ff7-547c013c14ea.jpg)
With DirBlur only 8 processes

![cimg_blur](https://cloud.githubusercontent.com/assets/8054856/6431228/21d298a8-c029-11e4-97c3-7a01fa506737.jpg)

With CImgBlur 24 processes (100% CPU)

**Comment by MrKepzie** [comment]
Your screenshot using the DirBlur node is taken at 0%. When rendering, Natron starts up a new thread at each frame, so the first frame will have only 1 parallel render, the second frame will have 2 etc... until it reaches the number of cores of your computer, i.e: 24.

For the rendering of 1 parallel frame, generally the maximum number of threads is limited to 8 (after that the performance decreases), that's why when rendering the first frame of the sequence, Natron is only using 8 threads.

**Comment by devernay** [comment]
We can't reproduce the bug, can you give more details or even send us the project?

BTW, I notice that you have a Transform after a DirBlur, which is a bad idea because the image is resampled twice. Did you know that? If you switch both effects, the transforms will be composed and the resampling done only once (a full explanation is given in Nuke User Manual).

**Comment by adallafontana** [comment]
You are right, is not a bug, the project was with 4k footage, I have test it with fullHD footage and only one DirBlur node that works well in multi-threading; the problem like said Devernay can depend from my erroneous node tree and many Shuffle node for divide channel and recompose, all was still freeze to the first  frames (....like said Alexandre) for a very long time rendering: looked like a freeze rendering, which not happen with CimgBlur because is faster that DirBlur.
You can close this issue, it was my fault.

Anyway I have a problem with shuffle, every time I have a shuffle node present on the comp tree all seem slowly, but I can't put at focus the issue for say if the problem is shuffle node.

a.
