### ISSUE TITLE
Copy nodes across projects

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#557]
It's critical to be able to copy a selection of nodes from one project file to another. This is needed just about any time you want to copy a nontrivial compositing operation from another project.

**Comment by adallafontana** [comment]
On snapshot version 2.0 you can select a node tree, create a Group, export as Group/Plugin and use
this one on other project like Macro or simple copy and paste on nodegrarph.

**Comment by Machiel-B** [comment]
Is there a way to link an exported group instead of creating a copy? So changes made to the .py automatically propagate into projects using the group?

**Comment by MrKepzie** [comment]
Unfortunately no, you have to re-export the group and overwrite it. 
Since it is a Python module, it is loaded on startup of Natron and any changes to the .py will not be taken into account till the next launch. 

Note that when using PyPlugs (.py groups), Natron will convert them to a regular group upon instantiation so that even if you don’t have the .py sticking around, it will still be able to load the project fine.

**Comment by Machiel-B** [comment]
I guess the conversion into a regular group is necessary, but it would be pretty nice if groups optionally remained linked to the .py. Maybe the group could keep a reference to the py, to allow replacing it with a newer version?

**Comment by MrKepzie** [comment]
There could be a preference of Natron where we could say the modifications made to a group would be saved to the .py automatically, but that would imply the following:
All the code that the user had written on its own in the .py will be wiped  (such as callbacks and so on).
All in all I don’t think  this is a great idea since one may then have this preference checked by mistake and not understand why the .py content is changed behind his/her back, causing loss of code

We have no way to isolate portions of code in the .py that were “automatically generated” and portions that were edited by the user (such as callbacks)

**Comment by Machiel-B** [comment]
I think we have a misunderstanding. I'm not proposing directly editing the group's .py. Au contraire, I want edits made in the .py. To propagate to instances of the group. Let's say I create a group that does some fancy effect.  I export this group as a .py. Now I start inserting the group in multiple .ntp files, but after I while I want to change the groups nodes, so I change the nodes and export the .py again. Right now I have to reinsert the group into every .ntp layout and reconnect it. What I propose is keeping these instances in the project files linked to the .py and 'refreshing' them (manually or on project load).

**Comment by MrKepzie** [comment]
Aight. The current approach has the following upside:
- One can just share the group without necessarily sharing the .py it is using as well
Downside:
- One can not have its project kept updated with new versions of the .py

The best thing I could do would be to come up with a slight modification:

If a .py exists for this plug-in, try to load it **only if the version of the plug-in is the same** instead of loading the group 

If a .py is not found, just load the group as usual

**Comment by Machiel-B** [comment]
For my purposes that would already be great. I guess adding a secondary check based on .py modification date or a hash and displaying a user notification or prompt (ok/cancel) would prevent users from getting confused.
I.e. "Natron has detected a newer version of blablalba plugin (path/file.py), would you like to update projectname.ntp?"

**Comment by MrKepzie** [comment]
Reopening and relabelling the issue

**Comment by MrKepzie** [comment]
This has been implemented, though no version checking is made yet
