### ISSUE TITLE
Enhancement: declare plugin ID constants at startup using plugin name

### ISSUE THREAD

**Issue by nicholascarroll** [MrKepzie/Natron#565]
When using createNode() its certainly more convenient to write
   ` createNode(Invert)`
rather than
    `createNode('net.sf.openfx.Invert')`
And the same is true wherever pluginID is used as a parameter. So at startup can you auto declare
     `Invert = 'net.sf.openfx.Invert' `
and so on for all plugins? If those variable names are not reserved then it would complicate the writing of scripts to share with others.

**Comment by nicholascarroll** [comment]
Regarding the problem of uniqueness, such as if you have several plugins called Invert, you could
- not declare them at all OR
- raise a nice exception
- just take the first one in the list

**Comment by MrKepzie** [comment]
This is not possible:

- Plug-ins define a "label" from which we initialise the variable that is available to Python upon construction, e.g:

app1.Read1 is instantiated when fr.inria.openfx.ReadOIIO is created because the plug-in label is "Read"

We cannot rely on an heuristic to say, "ok the plug-in ID will be ReadOIIO" because there could be multiple match and it could also conflict with node script-names.
The way it is is *fine* and makes sure of the uniqueness. If this is too much of a burden for you to use these long Ids, make your own variables list in the init.py script:

Invert = net.sf.openfx.Invert
Read= fr.inria.openfx.ReadOIIO
etc...

As long as the user is aware of what he/she does its fine, but we don't want to do this by default for him/her as it could lead to conflicting cases.

**Comment by nicholascarroll** [comment]
I understand. Yes, I'll make a list in init.py using getPluginIDs().
