### ISSUE TITLE
Natron-snapshots-b0db9e35667c2507a2be2e820be5887976881fc6: Merge node not passing color render data

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#576]
This Natron-snapshots-b0db9e35667c2507a2be2e820be5887976881fc6 version is not passing its Merge node data to the WriteOIIO node. The two attached images are proof the the WriteOIIO node is performing correctly because I connected the WriteOIIO node to each ReadOIIO node. The Last image shows the node setup where as the WriteOIIO node is connected to the Merge node and it renders just a white surface.
![btrack001](https://cloud.githubusercontent.com/assets/7956901/6801562/48180dee-d1ff-11e4-8a49-a5c1a1fc18a3.jpg)

![btrack001color](https://cloud.githubusercontent.com/assets/7956901/6801565/4c3d50f0-d1ff-11e4-8c1e-5fef7b593b67.jpg)

This image is the node tree setup in Natron where the Merge node is the last node in the comp before the WriteOIIO output.

![screen shot 2015-03-24 at 8 15 55 am](https://cloud.githubusercontent.com/assets/7956901/6801596/9371e6ca-d1ff-11e4-8bd7-ce30a6bea309.png)

**Comment by MrKepzie** [comment]
Omar this is not a bug, see https://github.com/MrKepzie/Natron/issues/352. The problem is that your alpha is filled of 0's but you're writing RGBA. Hence your file appears all black. Insert a shuffle node right before and you should be fine. 

The alpha channel is set to 0 by default to keep compatibility to how it works in Nuke, so it might be a bit disturbing for users which come from the After Effects world.

**Comment by blackearth2014** [comment]
Okay got it. I use to use the shuffle to keep the alpha channels from rendering from the roto nodes.
