### ISSUE TITLE
No plugin capable of decoding XXX was found

### ISSUE THREAD

**Issue by triceratops1** [MrKepzie/Natron#630]
I installed natron with the AUR package https://aur.archlinux.org/packages/natron/ but when i open a file a only recieve No plugin capable of decoding XXX was found

**Comment by olear** [comment]
You need openfx-io and openfx-misc. Contact responsible at Archlinux if they are missing or broken.

I recommend using the official binaries.

**Comment by MrKepzie** [comment]
This is not an issue relative to the code but on your installation (which is not the official provided by us btw). You should seek help on the forums instead.

**Comment by olear** [comment]
Btw, the AUR PKGBUILD is also no good, stuff is missing and installed in wrong locations, and of course no plugins.

I can make proper PKGBUILD's, if enough demand.... (i will not maintain them for Arch, but can make initial scripts for them to maintain, when/if I get the time). Also, will only work for v1.x, since Arch don't have the needed depends in repo for v2...

**Comment by triceratops1** [comment]
ok, for it i ask a small question.

can i make a PKGBUILD for the official binaries? "all ios installed at /opt and i crete a symlink to /usr/binNatron

natron-bin from the official binaries

**Comment by triceratops1** [comment]
my idea is a pkgbuild with same behavior of atom-bin or brackets-bin or gdevelop "it extracts the gdevelop package for ubuntu", i share the gdevelop "because i want make a similar work"
https://aur.archlinux.org/packages/gd/gdevelop/PKGBUILD

**Comment by olear** [comment]
If you choose to repackage the binaries use /opt/Natron for v1 and /opt/Natron-2.0 for v2. And symlink Natron, NatronRenderer and .desktop + icon.

That should work.

I can provide plain TGZ's instead of the installer if you want.

If you choose to build from scratch just ask if there is something your stuck on.

**Comment by triceratops1** [comment]
thanks!
