### ISSUE TITLE
Another binaries hosting?

### ISSUE THREAD

**Issue by TeddyDD** [MrKepzie/Natron#647]
Could you eventually consider another hosting for binaries than SourceForge? 
Taking into account the recent "trust issues" [here](http://helb.github.io/goodbye-sourceforge/) many people may feel insecure about downloading anythig from SF.

Personally I know how to compile it from source but do not expect the artists also can. 

Edit: I'm not sure but I think you can add binary files to github releases?

**Comment by olear** [comment]
A mirror? a new one? why?

**Comment by TeddyDD** [comment]
@olear Sorry, accidentally I sent the issue without description :blush:

**Comment by olear** [comment]
Know about the issues with SF, but personally I think it's a bit exaggerated. I have several project on SF, and have no plans on moving them yet.

Github does not support the way Natron is distributed for Linux and for the snapshots. But for major releases there should be no problem to add binaries attached to the tags.

There are currently back-end changes in the project, and moving the binaries may or may not be in those plans.

**Comment by TeddyDD** [comment]
Thanks for quick respond
>personally I think it's a bit exaggerated.

Personally, I won't download anything from service which I can not trust. Call me paranoid or idealist ;)

I hope of being at SF won't negatively affect this awesome project in any way.
Please close this issue if appropriate

**Comment by olear** [comment]
As long as the checksums are in order SF is safe. As said the current infrastructure for distribution of Natron binaries won't work on Github, so SF will be use until Github adds proper files hosting, or we move to private servers, but remember that costs money and extra maintenance ;)

Some of the Natron (web) infrastructure will soon be moved to servers controlled by Natron, but it's unsure if the file downloads also will be hosted there as well (due to the extra costs etc).

**Comment by TeddyDD** [comment]
If you say so Im closing this then
