### ISSUE TITLE
Merging more than two inputs has disappeared

### ISSUE THREAD

**Issue by crydalch** [MrKepzie/Natron#657]
After updating to the latest builds of Natron, it appears that the ability to merge more than two inputs has disappeared (see issue #446).

Could this be restored?

Thanks!

**Comment by MrKepzie** [comment]
Is it back?:p

**Comment by crydalch** [comment]
I can't get it to build on my machine, but I saw your commit for it, and as soon as the Linux64 update is available through the Maintenance Tool, I'll verify and update here.

Thanks for jumping on this so quickly!

**Comment by crydalch** [comment]
Sorry I got pulled away for a while! Yeah, it seems to be back, thanks!

I was confused for a few moments, because of issue #687, but all is well! 

Cheers!

**Comment by oxydenz** [comment]
Hello, 
Ok, maybe i'm just coming back on a closed topic since three years.... 
I found this thread looking for a way to have two blurred shapes simultaneously on a sequence (typically to hide faces on a documentary)... I have to apologize cause i'm really newbie on Natron ( but have a good experience, something outdated, on proprietary softwares.... so , maybe i'm doing it wrong.... better than too much words:
![natron2blurs](https://user-images.githubusercontent.com/37882629/38054710-10fe236a-32d8-11e8-8739-4bd97376c6b2.png)
My first blurred zone is ok, but setting the second one deactivates the first...
I'm working on a Debian 9 with Natron version 2.3.8
Thanks for all !!

**Comment by devernay** [comment]
@oxydenz this is a simple issue that requires a longer explanation, please ask on forum.natron.fr
