### ISSUE TITLE
RotoPaint Pencil tool doesn't allow interpolation changes

### ISSUE THREAD

**Issue by hpetrus** [MrKepzie/Natron#713]
The newly introduced Pencil tool in the RotoPaint node only plots a single 'Animation' curve in the curve editor (is this intentional?) and doesn't allow value changes (time changes work fine), nor any interpolation changes.

This is the case on GNU/Linux variants of all kinds.

Thanks for looking into this.

**Comment by MrKepzie** [comment]
the animation curve is not meant to be moved in value: the value just indicates the index of the keyframe, it does not hold any meaning besides that.  Also, you cannot set anything else than linear interpolation because it would be more complex to interpolate tangents of the control points so that they follow exactly the bezier animation.
