### ISSUE TITLE
Shuffle node: allow to create alpha channel if input is RGB

### ISSUE THREAD

**Issue by MrKepzie** [MrKepzie/Natron#765]
Add a checkbox "Create alpha" when input is RGB

**Comment by devernay** [comment]
In Nuke (recent version), there is a chechbox in the reader to add an opaque alpha channel. This looks like a good alternative to me.

**Comment by Phantom-Studio** [comment]
sometime it s useful to be able to set alpha to 1 (or 0) somewhere in your tree and not in the reader.
Because you can have some alpha manipulation upstream and then need to change it.
Have this option in shuffle avoid to create and pipe a constant in a shuffle node.

**Comment by MrKepzie** [comment]
implemented

**Comment by devernay** [comment]
This was already possible in the previous version (you can set any existing channel to 0 or 1)
That request was about adding an alpha channel
Le 23 juil. 2015 12:18, Phantom Studio <notifications@github.com> a écrit :sometime it s useful to be able to set alpha to 1 (or 0) somewhere in your tree and not in the reader.
Because you can have some alpha manipulation upstream and then need to change it.
Have this option in shuffle avoid to create and pipe a constant in a shuffle node.

**Comment by MrKepzie** [comment]
This is exactly what is implemented
