### ISSUE TITLE
MetaData 

### ISSUE THREAD

**Issue by Phantom-Studio** [MrKepzie/Natron#783]
hello, 
Is there a way to preserve exr's metadata when I render a comp.
to be more precise, i have a plate (exr files) from a red epic, with a lot of metadatas(shutter, color balance and lot more), I comp my 3D into this plate and i would like to keep all the metadata in the render.
if there is no way , it would be nice to have a few nodes to manage them (copy metadata, set metadata, and optionally remove metadata).

**Comment by devernay** [comment]
This should be done on the openfx side: http://openeffects.org/standard_changes/metadata
As soon as the proposed OFX specs are made clearer, we will implement them.
In the mean time, can you check that you can see all your metadata when you click "Image info..." in the reader's properties panel?
If the metadata is the same for all images, we could probably hack something for 2.1.

**Comment by extrinsicmedia** [comment]
Take a look at Component 3 in this:
http://www.openexr.com/openexrfilelayout.pdf

```
The header of every OpenEXR file must contain at least the following attributes:
attribute name attribute type
channels chlist
compression compression
dataWindow box2i
displayWindow box2i
lineOrder lineOrder
pixelAspectRatio float
screenWindowCenter v2f
screenWindowWidth float
```

There are many times that Red or Alexa derived EXR's will have useful camera data that needs to be parsed, manipulated, or passed through for correct ingestion by a DI facility.

Sometimes a client will want specific timecode metadata transferred from a second source via a copy of the metadata from one stream/pipe to another as well.

I would think that metadata reading, writing, copying, and general user manipulation should be a core node and is needed ASAP.

**Comment by rickgrandy** [comment]
While an OFX standard would be nice, since most comp apps already have the capabilities to deal with metadata, it doesn't seem to be a fast moving issue.  No one needs a plugin for it and the image containers store it just fine.

For us (and may others), the ability to read, manipulate and write metadata is critical.  I don't think an OFX standard is required as this should be core functionality within Natron and honestly it's the reason we have not rolled it out for wider testing in production.  We can't even use Natron for batch processing at the moment since maintaining and manipulating metadata are primary features of our automated processes. (injecting timecode, managing colorspace, etc)

But we'll keep checking back...

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#105
