### ISSUE TITLE
nodegraph 'navigator' issue

### ISSUE THREAD

**Issue by rcspam** [MrKepzie/Natron#819]
The navigator is not handle corrently:
[screenshot](https://dl.dropboxusercontent.com/u/2677320/screenshot-2015-08-06_18.57.29.mp4)

**Comment by sebloss** [comment]
Indeed navigator is weird. It's hard to target a specific area.
It seems made with an intelligent bounds adaptation but it doesnt work well. Often out of focus

**Comment by sebloss** [comment]
Say we have a virtual unlimited node graph canvas.
Navigator is one domain of this canvas and help us to move our working area while this area is smaller than our domain (zoom in). Mouse drag view using delta pos multiply by inverse of zoom factor or something like this ( i'am a bad student). Anyway, this is a linear function.
Ok. Now we need to define domain boundaries.
In Nuke boundaries are defined by the whole graph boundaries , this makes totally sense.
Navigator help us to navigate and work on graph. not the empty infinity space. Say an graph focused navigator.
Natron navigator boundaries varies accordingly union of graph and view bounds.
Mouse click on visible graph in navigator works well because boundaries barely change.
But when mouse drag is another story , domain is constantly changing make it behave like view (zoom and pan). Natron navigator is a view of a view of canvas. Mouse drag equation is not linear at all with a changing centroid. It is not human predictable, doesnt make sense and not very handy.

Could Natron navigator be more simple ?

**Comment by MrKepzie** [comment]
This is due to how internally QGraphicsView works. There is nothing we can do about it, except recode it ourselves.

**Comment by MrKepzie** [comment]
See https://github.com/MrKepzie/Natron/issues/815
