### ISSUE TITLE
Give the timeline it's own panel

### ISSUE THREAD

**Issue by azerupi** [MrKepzie/Natron#870]
At the moment each viewer has it's own timeline, but all the viewers seem to be synced together (which is a good thing). Therefore having a timeline for every viewer seems a bit redundant. Unless I am missing something.

To have a bigger timeline and save screen estate it could be a good idea to give the timeline a panel of its own. You could then have 1 timeline for multiple viewers and place it somewhere else in the layout, independently of the viewers.

**Comment by manuelsongokuh** [comment]
yes, i'm agree @azerupi 
because i have dual monitors i want to free all things and one to show viewer (nothing buttons,etc) because i want to see second montors for full video like as true size hdfull nothing stuffs..

if cant to remove all stuffs then NEEDED like ask:
![link](https://cloud.githubusercontent.com/assets/4058448/4984585/49e92a92-6925-11e4-98ad-0f6d0d2834d4.png)

or like  Blender like Back Drop:Request #317

**Comment by azerupi** [comment]
Couple of other notes about the timeline:

- **Inter-frame graduations** I am not sure how useful that is since you can't put the time cursor between frames. I would remove them
- **Zoom** I can't imagine a situation where you would need to zoom in more than 10 frames on the timeline. I would therefore limit the zoom level to have minimum 10 graduations (frames) on the timeline instead of the current 2 graduations. Especially if you remove inter-frame graduations
- **Default frame range** This is more of a preference but, I think a default frame range of **± 1-250** (10 seconds) would be better than the current 1-1

**Comment by manuelsongokuh** [comment]
i want to understand:

new panel: only timeline like "split-off" from PANEL OF VIEWER, i'm needed this...why?
because i can see to PANEL VIEWER like FULL CLEAR, nothing: timeline,zoom, frame range.
.
this mean:
- split timeline to new panel
- split zoom to new panel
- split frame range to new panel
so this panel of viewer: have only to see result. future can add new stuff like as: name viewer, frames, checker to background, fps, Screencast keybord+mouse..this is good for develop for code and easy to add and growup..

all of this: i'm not sure for team develop.. this is for feature request and not bug,it's right?

i have tired for second monitor i have second viewer but there is timeline,zoom,range..i cant to see full size like monitor hdfull 1920x1080..

i'm interesting this issue..

**Comment by azerupi** [comment]
@manuelsongokuh is that a question for me?

The way I see it:

It doesn't make any sense to have one timeline and playback controls for every viewer since they are synced together. Therefore I would move those in a separate panel. The viewer specific options on the other hand should stay in the viewers panel. Eventually with a shortcut to hide them if you don't need them.

What I mention in my second post are other *painpoints* related to the timeline but not related to the timeline having it's own panel.

I hope this clarifies some things

**Comment by devernay** [comment]
@azerupi all these requests make sense to me

**Comment by sirdavid32** [comment]
A global (only) pannel is what Azerupi is proposing. I also see it as a waste of space having a timeline (and all it´s controls -by default- on each viewer). There could also be a right click->hide timeline on this viewer option.

**Comment by devernay** [comment]
I implemented enhancements to the timeline GUI (#917). In a future version, the timeline, dope sheet and curve editor will be reworked together.

**Comment by azerupi** [comment]
Thanks! 
Especially for the panning with middle-mouse button :)

**Comment by mash-graz** [comment]
> split timeline to new panel

if you have more than one viewer on the screen, it can make a lot of sense to lock/unlock them from the frame number of other viewers for visual reference etc. an extra panal would make that more complicated than necessary.

**Comment by nicholascarroll** [comment]
I thought alot about this and I now think that all that is needed to implement this is a default:
*When you open a new viewer and there is already at least one open, default the timeline and player to hidden on the new viewer*.

**Comment by devernay** [comment]
This issue was moved to NatronGitHub/Natron#114
