### ISSUE TITLE
Generators: issues when changing frame range

### ISSUE THREAD

**Issue by olear** [MrKepzie/Natron#910]
Start Natron, add a generator (plasma), all is good, but add 10 frames and everything turns black, and scrubbing don't work. Detach the generator node from viewer and reattach fixes the issue.

**Comment by MrKepzie** [comment]
It's a slight bug in the UI:

When pressing Return in the Line Edit of the frame range of the viewer, Qt emits the editingFinished() signal but does not accept the event, hence passing it to the parent ViewerTab... which interprets the Return by default as switch input A and B. Since you probably have nothing in B, it just switches A to black and you don't see anything. I've fixed that in LineEdit
