### ISSUE TITLE
ReadFFmpeg performance issue: Can't play a H.264 1080p movie at real time

### ISSUE THREAD

**Issue by genete** [MrKepzie/Natron#951]
When loading a 1920x1080 H264 MOV file and connect it to the default viewer, can't play it at real frame rate (24 fps). It plays at 5 fps.
According to the features:

*Performances:  Never wait for anything to be rendered, in Natron anything you do produces real-time feedback thanks to its optimised multi-threaded rendering pipeline and its support for proxy rendering (i.e: the render pipeline can be computed at lower res to speed-up rendering).*

so, I should be able to playback a movie in real time.
My computer specs are:
iMac 27 inches 2011
Processor: 2,7 GHz Intel Core i5
Memory: 20 GB 1333 MHz DDR3
Graphics: AMD Radeon HD 6770M 512 MB

**Comment by devernay** [comment]
how long is you movie (number of frames) ?
We will optimize reading video files in Natron very soon (hopefully before 2.0)

**Comment by devernay** [comment]
Here is the reason:
when several threads are rendering, they ask for frames from the reader in a random order. Consequently, a signe frame may have to be decoded several times (define TRACE_DECODE_PROCESS in FFmpegFile.cpp, and check how many times "Seeking to desired frame" is printed out).
Here are the steps (for internal use):
- FFmpegReader should implement getFramesNeeded(const OFX::FramesNeededArguments &args, OFX::FramesNeededSetter &frames), which should (on Natron only) set the interval of frames (without the asked one) that will have to be decoded in order to decode a frame, by setting the proper interval on its *output clip*
- when Natron gets the result on getFramesNeeded on any effect, if there are frame intervals on the output clip of the current effect and kOfxImageEffectInstancePropSequentialRender=2 on the effect, it should render from the first frame of these intervals which is not already in cache to the current frame in a single SequentialRender.

**Comment by genete** [comment]
It is a 30 seconds movie @25 fps

**Comment by olear** [comment]
This should have been fixed in 2.0.1? Please re-open if not.
