### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [MrKepzie/Natron#968]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/MrKepzie/Natron/blob/d3592427d36cb43eef2ff74677c2a191bf8c528e/App/NatronApp_main.cpp#L46 "main() function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "Uncaught exceptions") like they are described by Danny Kalev?

**Comment by devernay** [comment]
we don't catch exceptions in main() because they should be caught in proper places.
Catching in main() in our case is useless: Natron is a GUI app, so exception that would be caught by main could not be signaled to the user.
A few exception may not be caught, but they are all signaled by coverity scan, see https://scan.coverity.com/projects/mrkepzie-natron
We fix these at each scan.
This is much better than adding a try..catch in main.

**Comment by elfring** [comment]
I guess that [the mentioned source code analysis service](https://scan.coverity.com/projects/mrkepzie-natron "Checking by Coverity Scan") does not help in improving [this issue](http://stackoverflow.com/questions/8311457/are-destructors-called-after-a-throw-in-c "Are destructors called after a throw in C++?").
Do you care for implementation-defined behaviour from the general structure of your function "main"?

How do you think about to add the following items there?
* Catching [the exception "std::bad_alloc"](http://en.cppreference.com/w/cpp/memory/new/bad_alloc "Allocation failure") explicitly
* [Catch-all clause](http://en.cppreference.com/w/cpp/language/try_catch "try-block")
