### ISSUE TITLE
Viewer: add OCIO colorspace conversion shaders

### ISSUE THREAD

**Issue by sobotka** [MrKepzie/Natron#982]
Where are the View transforms pulled from in the view window? It doesn't appear to be using the selected config's views, as they would correct the primaries.

![view-lut](https://cloud.githubusercontent.com/assets/59577/10749668/58d8765c-7c2a-11e5-9a77-9132c52aa4cc.jpg)

It is also quite alarming that there is an input and output colourspace in the Read node, where there shouldn't be such.

There should only be a colourspace for the image, which is used to transform it to and from the reference space.

**Comment by MrKepzie** [comment]
This is in the todo list. We don't have implemented yet the GPU shaders using OCIO for the Viewer colorspace conversion. Currently these are built-in luts within Natron.
The only way currently to overcome this and use a OCIO colorspace is by putting a OCIOColorspace node before the viewer.

**Comment by sobotka** [comment]
I remain a wee tad concerned at the “Input” and “Output” colour space options. I may well be incorrect in that it strikes me as an ICC based approach, which OCIO isn't.

The Read node should merely supply the image's colourspace as per the transforms listed in the OCIO config. OCIO then will transparently handle all transforms into and out of the Reference space, which is specified elsewhere in the application globally.

The idea of an Input and Output explicitly breaks OCIO's management abilities.

**Comment by MrKepzie** [comment]
The input/output colorspace options of the Reader are automatically guessed and set by Natron (in fact the openfx-io plug-in). 
These settings are there in case the file is not well encoded or if the user wants to output something different than Linear colorspace. 
You can anywhere in the pipeline change the colorspace with a OCIOColorSpace node (which does exactly what is built into the Read node). 
Then the Write node does the opposite and guesses automatically the output file colorspace and converts from (assumed) Linear to Output colorspace. 

If the pipeline is not meant to be Linear, then one should pay attention to Reader nodes output colorspace and Write nodes input colorspace. 
The viewer needs also to be currently adjusted by prepending a OCIOColorSpace node before it and setting the Viewer to “Linear” in the dropdown.

**Comment by sobotka** [comment]
OCIO is predicated on a reference space for manipulation always being a linearized version.

The Read node just confuses the issue and mixes / multi-tasks a single node to doing the work of other nodes. It also increases the odds of a misconfigured and mismatched reference without any gain.

Finally, the colour sampler is completely confused by the pipeline outlined above as the reference data is occluded by the sampling of the display buffer?

The colour sampler *must* sample the reference space, not the post-transformed display / view buffer.

**Comment by MrKepzie** [comment]
The Read node Input/Output colorspaces option as said are set automatically and there should be in most cases no need to tweek them. 
However there might be cases where the detection from the file header might be wrong, and they are here for advanced users. Maybe this should be in a advanced tab. 

I’m not too sure about what you call the colour sampler, so I’ll assume this is the colour picker informations under the Viewer: The info displayed are the internal values of the images (Linear if the images were kept linear). The small coloured square label however has the Lut of the Viewer applied on it so it ressembles the colour on the Viewer.  There is no meta-data for the colorspace circulating throughout the graph. The user is supposed to know what she/he is doing. This could be an enhancement though to make it clearer.

**Comment by sobotka** [comment]
> The Read node Input/Output colorspaces option as said are set automatically and there should be in most cases no need to tweek them.
> However there might be cases where the detection from the file header might be wrong, and they are here for advanced users. Maybe this should be in a advanced tab.

Unless you have added something to OCIO with LCMS, there is no detection, merely the defaults set based on bit depth.

I would strongly reconsider the input / output UI paradigm as it is entirely not what OCIO intends for an image. If, for some edge case need, the colourspace of the data needs to be transformed *in the reference space*, it can be achieved with the OCIO node.

An OCIO pipeline is designed to handle all of the transforms to and from reference. The more proper approach would be precisely as Nuke has it, with a singular variable that defines the image's colour space. The existing paradigm appears to be modeled after ICC patterns, which would be entirely incorrect.

I will attempt again to get a compile and check the code paths.

**Comment by devernay** [comment]
default file (i.e. input for reader, output for writer) colorspace is based on:
- file name, as used in the SPI workflow (implemented in OCIO, so *yes* there is colorspace detection in OCIO)
- if no colorspace can be found from the file name, look into the file metadata (not implemented in OCIO, implemented in OIIO)
- if no colorspace metadata is available, fallback to a reasonable default (implemented in the Reader plugins)

Since there are always cases where this information is wrong, the user can still change the file colorspace (as well as file premultiplication).

The default for a reader output or writer input colorspace is always linear, but it does not have to be linear. The user always has the control over this, and there are operations that do not require using a scene_linear space (transcoding, reformating, cropping are such examples).

**Comment by sobotka** [comment]
> Since there are always cases where this information is wrong, the user can still change the file colorspace

My issue wasn't with the changing of colourspace, but rather the notion that it should be input / output based.

Typically it would simply be by changing the image's colourspace. In doing so, the image always remains in reference space and OCIO handles the transforms. By using an input / output concept, it degrades the concept of reference space.

 > The user always has the control over this, and there are operations that do not require using a scene_linear space (transcoding, reformating, cropping are such examples).

These examples are a smidge confusing, such as cropping for example.

That said, there is a tremendously useful concept in here for outputting to display referred domains such as JPEGs, TIFFs, DPXs, etc.; the idea of a transform configuration for baking output transforms. It might be more elegant than a chain of transform nodes.

**Comment by MrKepzie** [comment]
Implemented in https://github.com/MrKepzie/openfx-io/commit/8a712e157844cf5c0cb915e5446eaa1e48a33df3

Now we just need to interface the Natron's viewer so it uses internally the OCIO* nodes instead of the fixed built-ins luts and that's it

**Comment by sobotka** [comment]
Well done guys.

I would also encourage revisiting the notion of reference space (remove input / output chains) as was marked to-do.

Strong work.

**Comment by MrKepzie** [comment]
@sobotka You said a few posts above that Nuke gets its right by not proposing you the input/output options, but just input (for Reader) and just output (for Writer) hence forcing you to accept that internally they convert everything to linear.  I don't see where Natron is much different, except that we allow that processing takes place in another colorspace than linear. For what I know, by default After Effects does not apply any colorspace conversion and users are OK with it, so we might imagine Natron having a fast 8-bit, straight, sRGB pipeline too. Things is input/output brings more flexibility than just enforcing internally a linear pipeline.

Anyway, we are open to discussion!

Anyway as a side-note, what we wanted to do for the next version of Natron is to replace the viewer node by a group, in which the Output node would be the internal viewer process, which would be connected to a OCIODisplay node and to its respective inputs. The user could then add nodes in this sub-graph, without modifying the "main-graph", and he could expose parameters of his choice of the sub-graph nodes onto the viewer UI directly.

Problem is, even with OpenGL shaders, OCIO nodes aren't faster that our built-in Luts (sRGB/Rec709) we use currently for the display.  The bottleneck is the following:

- On very small graphs (Reader-OCIODisplay-Viewer) there are a limited number of OpenGL context that each render threads can share (by default its 2 in Natron, but can be increased, on my mac more than 4 concurrent OpenGL contexts starts to freeze the OS). On the CPU path in Natron, all CPU threads just concurrently compute the graph at each different frame. With GPU path, only threads with an associated OpenGL context can do the work, and others are waiting trying to lock an available OpenGL context. 

- Natron needs to bring back the OpenGL texture returned by OCIODisplay on the CPU for 2 reasons:
1) Caching: if we don't cache at this point, then playback will not be fast
2) Currently Natron still uses Qt 4.8 and it's impossible to share the OpenGL context used by QGLWidget and our internal OpenGL contexts we use for rendering, hence the texture returned by the graph cannot be used directly on the widget and must be transferred onto CPU first. In Qt5 it is possible to share the QGLWidget OpenGL context to a custom OpenGL context but we are not yet on Qt5 (even though Natron works fine with it).

Problem is:
-  playback of an HD sequence here without OCIODisplay (Reader-Viewer) with sRGB built-in turned on in the viewer, I get 27fps 
- playback of the same sequence but with a graph Reader-OCIODisplay-Viewer without built-in lut but with OCIODisplay device set to sRGB, I get 15fps

That's a 12fps difference, people won't like that by default.
So I'm hesitating into leaving default in the viewer graph to our own built-in luts, BUT having possibility to use OCIO nodes into the viewer graph, so that advanced users may still enjoy using them.

**Comment by sobotka** [comment]
> @sobotka You said a few posts above that Nuke gets its right by not proposing you the input/output options, but just input (for Reader) and just output (for Writer) hence forcing you to accept that internally they convert everything to linear.

A couple of points that are worth embracing:
 * Linear is not a colour space.
 * Everything in OCIO is stated in relation to a reference space. That is, all transforms do not exist unto themselves, but in relationship to the transforms outlined in the configuration.

For these reasons, the concept of a reference is fundamentally crucial to keep the integrity of the data.

By providing an input and output, given they are OCIO transforms, you effectively break the internal protocol of any notion of a colour space.

Yes you *can* achieve this with a unique OCIO node in a chain, which is ideally an exceptional circumstance for knowledgeable imagers. Hence why it is vastly more sane to keep to the internal protocol for OCIO and avoid explicitly overriding the framework's intention on a read.

> So I'm hesitating into leaving default in the viewer graph to our own built-in luts, BUT having possibility to use OCIO nodes into the viewer graph, so that advanced users may still enjoy using them.

This is not an advanced user scenario. Modern pipelines are likely 0% to be using 709 primaries or home grown transfer / spaces. Much more likely is the idea to use DCI-P3 or REC 2020 primaries, or even more likely, a properly wrapped and tight ACES pipeline.

Hence the idea that a compositor can survive the modern era using anachronistic 709 primaries or sRGB built-ins is a naïve anachronism that would relegate the tool to a hobby application.

**Comment by MrKepzie** [comment]
I agree that the usefulness of the **Output ColorSpace** (for the Read node) and **Input ColorSpace** (for the Write node) are to be questioned and are probably useful for a handful of well advanced users, but even then they could use a OCIOColorspace node to fix the transformation. 
So it rather confuses users than provide something really needed.
This is something we will discuss with @devernay .

I understand that it may be widespread common practise to work with a fully managed colour processing pipeline nowadays. 

However, you can still see that Nuke (which is not a hobbyist application) by default proposes you their built-in (hardcoded) 1D Lut, and this is the user own responsibility to change this by going to Preferences and switching the OCIO config to something else than nuke-default, in which case instead of proposing you the basic hardcoded luts, it proposes you the display devices bundled in the selected OCIO config. 

Anyway,  this is a very superficial discussion because in Natron 2.2 it will be very easy to expose whatever parameter you want (as a user) in the toolbar ontop of the viewer (or even in the player)
and we could even by default have a OCIODisplay node within the Viewer group with its *Display Device* parameter already linked into the top toolbar of the viewer to replace what is the current *viewer color process* combobox. 

I agree also that any professional wanting to do accuracy and quality imaging will take time to understand all this process.

Anyway, just as a side note, note that the rest of users (98%) don't really care about colorspaces, bit depth, alpha premultiplication and so on, as long as they can encode their files (in whatever format they first pick) and apply some animation to objects.

We really strive for making a professional quality tool, but we can't help but see that a lot of people use our software and don't understand a single thing about how it works

**Comment by sobotka** [comment]
> Anyway, just as a side note, note that the rest of users (98%) don't really care about colorspaces, bit depth, alpha premultiplication and so on

That is a cultural problem, that, with a bit of care and attention and knowledge, can hopefully be corrected.

I have yet to find a single imager that doesn't care tremendously when the various concepts are explained in a manner that is clear to them.

At any rate, great work on trying to bolt down the complexities of solving a core design issue.

**Comment by MrKepzie** [comment]
It's not so much of a conception problem, rather we try to make the user able to customize every bit of the display pipeline, Natron can be modified a lot just with OpenFX plug-ins as internally everything runs through OpenFX nodes

**Comment by MrKepzie** [comment]
This is how it looks in master branch now. User can customize the viewer as it wishes and save it as a preset when making new viewers:

![screen shot 2016-08-22 at 14 53 20](https://cloud.githubusercontent.com/assets/4058448/17855339/90050b8c-6878-11e6-98c3-05db4a8e11fd.png)

In the above screenshot, the Device parameter in the viewer top toolbar is merely an alias created by the user of the parameter in the OCIODisplay node used inside the Viewer1 sub node graph.

I will add this configuration by default with a checkbox

**Comment by MrKepzie** [comment]
Quick update, I added a ViewerOCIO PyPlug by default to Natron which you can create from Image-->ViewerOCIO

It has the following layout by default:

![screen shot 2016-09-30 at 18 46 50](https://cloud.githubusercontent.com/assets/4058448/18999528/666152e2-873e-11e6-90c1-a64a84451c26.png)

I linked the OCIO display device and view transform parameters to the viewer toolbar. User can customize it more, this serve merely as an example

**Comment by rebuilder** [comment]
Good to know! Eagerly waiting for Natron 3, then!

**Comment by MrKepzie** [comment]
Checkout the master branch of Natron. The viewer node is now a group which can also be exported as a PyPlug. I have to refresh the ViewerOCIO though to reflect recent changes. It's pretty easy to make a new one, just edit the viewer subgraph, you can add parameters in the top toolbar of the viewer etc...
