### ISSUE TITLE
roto bezier mode issue ?

### ISSUE THREAD

**Issue by mathiastesar** [MrKepzie/Natron#990]
well i m not so sure about that one.
I have two bezier curves to make a roto on a tire.
the upper one is in "minus" mode to make a hole.
if i test with a grade node it doesn t seem to work, it should be the same result as if it was on "from" mode (attached file).
In nuke it gives me the same result but maybe the calculation order in layers is not the same in natron
![layer_mode](https://cloud.githubusercontent.com/assets/15384202/10833209/a63fad14-7e66-11e5-9562-f5aee00ff88f.png)

**Comment by MrKepzie** [comment]
I think this is rather a bug in Nuke, see the following screenshots. 
Both in Natron and Nuke, the shapes are rendered from the bottom of the list to the top of the list (so that the top one will be the last one rendered on top of the others). 

Note that the blending operator selected for a shape specifies how the rendering of the corresponding shape will be rendered on top of the others ones in the bottom of the stack. 
In other words it is just a Merge operator where A is the render of the inner stroke and B is the render of the outter stroke.

Roto is setup to output in the alpha channel with a value of 1; thus merging with a Minus operator (i.e: A - B) will give 0 where the inner stroke is defined and -1 where the inner stroke is not (0 - 1 = -1).

In Nuke the Minus operator on the roto shape yield the following:

![minusnuke](https://cloud.githubusercontent.com/assets/4058448/10885112/ea85691a-817b-11e5-9405-3ef1ee65e77a.png)

which is wrong: it is 0 inside, but **1** outside of A, instead of -1!

You agree that the result should be the same that if I did my 2 shapes in 2 separate Roto nodes and applied a Merge node to them, but you can see that this is not the case. This time the result is correct and there are -1 outside of A:

![mergenukewithnodes](https://cloud.githubusercontent.com/assets/4058448/10885224/7e9d6bca-817c-11e5-8798-8c2dd3f0f412.png)

In Natron the result is correct: 
<img width="1552" alt="minusnatron" src="https://cloud.githubusercontent.com/assets/4058448/10885241/97f49058-817c-11e5-92e4-ae0d807d6cb3.png">


The **from** operator (B-A) is the correct operator to use in that case: You want the Roto's output to be 0 in the inner shape and 1 outside of A (and inside of B).

The results are then identical for me in Natron and Nuke:

Nuke:
![fromnuke](https://cloud.githubusercontent.com/assets/4058448/10885306/ec18f5a2-817c-11e5-89fa-0714f09428fe.png)

Natron:
<img width="1552" alt="fromnatron" src="https://cloud.githubusercontent.com/assets/4058448/10885314/f1c3e80e-817c-11e5-9006-5bd0a955343f.png">

**Comment by MrKepzie** [comment]
If you agree, you can then close this

**Comment by mathiastesar** [comment]
Hi !
Yep indeed, let s close that one !  ;^)

2015-11-02 10:16 GMT-05:00 Alexandre Gauthier <notifications@github.com>:
